### ISSUE TITLE
Start Script don't work

### ISSUE THREAD

**Issue by netzulo** [OxideMod/Oxide#1003]
- Steam Account : 👍 
- Requirements : 👍 

> 15:14 [Info] Loading Oxide Core v2.0.0...
> 15:14 [Info] Loading extensions...
> 15:14 [Info] Loaded extension CSharp v1.0.0 by Oxide Team
> 15:14 [Info] Loaded extension JavaScript v1.0.0 by Oxide Team
> 15:14 [Info] Loaded extension Lua v1.0.0 by Oxide Team
> 15:14 [Info] Loaded extension MySql v1.0.0 by Oxide Team
> 15:14 [Info] Loaded extension Python v1.0.0 by Oxide Team
> 15:14 [Info] Loaded extension SQLite v1.0.0 by Oxide Team
> 15:14 [Info] Loaded extension Unity v1.0.0 by Oxide Team
> 15:14 [Info] Loaded extension TheForest v1.0.0 by Oxide Team
> 15:14 [Error] Failed OnModLoad extension TheForest v1.0.0 (NullReferenceException: Object reference not set to an instance of an object)
> 15:14 [Stacktrace]   at Oxide.Game.TheForest.TheForestExtension.OnModLoad () [0x00000] in <filename unknown>:0 
>   at Oxide.Core.Extensions.ExtensionManager.LoadAllExtensions (System.String directory) [0x00000] in <filename unknown>:0 
> 15:14 [Info] Using Covalence provider for game 'The Forest'
> 15:14 [Info] Loading plugins...
> 15:14 [Info] Loaded plugin Unity Core v1.0.0 by Oxide Team
> 15:14 [Info] Loaded plugin The Forest v1.0.0 by Oxide Team

Downloaded oxide proyect and compiled TheForest, copied *Bundles/TheForest* to my installation client directory , maybe that's the problem...

[oxide_2017-01-21.txt](https://github.com/OxideMod/Oxide/files/721201/oxide_2017-01-21.txt)

**Comment by lukespragg** [comment]
Please use our forums for general support. We do not currently support The Forest though.

**Comment by netzulo** [comment]
okey! thank you for your time.
