### ISSUE TITLE
Can't set hostname in The Forest

### ISSUE THREAD

**Issue by isrever** [OxideMod/Oxide#1004]
when starting a forest server, the name is always 123.
Thanks

**Comment by lukespragg** [comment]
The hostname is set via your startup .bat script. It has never been "123" as a default, and is actually "My Oxide Server" in the example .bat we include.

**Comment by isrever** [comment]
Thanks this is what i have set. 
TheForest.exe -batchmode -nographics -ip 0.0.0.0 -port 27016 -maxplayers 10 -hostname "test server" -friendsonly 1

though this also seems to create multiply servers. e.g. the server list populates with about 10 or so servers callerd 123.

Thanks for your help so far, really quick responce

**Comment by isrever** [comment]
p.s. i was using the latest snapshot if that makes a difference

**Comment by isrever** [comment]
I fixed the issue, i found out that if i created a server through the forest using host then quit the server, the oxide server details were overriden by  the details that, i had previously entered.
so i have entered all the details using the host feature in the game and now  it works perfectly when i quit and re-host using oxide. 
Thanks again
