### ISSUE TITLE
Could not find a part of the path *logfile here*

### ISSUE THREAD

**Issue by ExoKalork** [OxideMod/Oxide#1020]
About half the time I get the error "Could not find a part of the path "/home/steam/serverfiles/server/my_server_identity/oxide/logs/PluginName_2017-2-4.txt"." on server startup, even thought my server Identity is not "my_server_identity".

Here is how I write the file:
`ConVar.Server.Log(@"oxide/logs/PluginName_" + DateTime.Now.Year + "-" + DateTime.Now.Month + "-" + DateTime.Now.Day + ".txt", message);` and it is called the first time in the Loaded hook.

**Comment by lukespragg** [comment]
We do not support Rust's methods such as ConVar.Server.Log. I'd recommend using our LogToFile method instead, as the path is not always guaranteed with the ConVar.Server.Log method. Also, for general plugin development, please use our support forums. This is primarily a bug and issue tracker for Oxide.

**Comment by ExoKalork** [comment]
Thanks for the answer. And my bad, I thought it was an Oxide function.
