### ISSUE TITLE
Linux server will not start

### ISSUE THREAD

**Issue by cokll** [OxideMod/Oxide#1022]
`Found path: /RustDedicated
Mono path[0] = '/RustDedicated_Data/Managed'
Mono path[1] = '/RustDedicated_Data/Mono'
Mono config path = '/RustDedicated_Data/Mono/etc'
Initialize engine version: 5.4.2f2 (b7e030c65c9b)
Forcing GfxDevice: Null
NullGfxDevice:
Version:  NULL 1.0 [1.0]
Renderer: Null Device
Vendor:   Unity Technologies
AudioManager: Using Unknown: NoSound Driver
Begin MonoManager ReloadAssembly
Loading /RustDedicated_Data/Managed/UnityEngine.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Assembly-CSharp.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Assembly-UnityScript-firstpass.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/UnityEngine.UI.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/UnityEngine.Networking.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/UnityEngine.Analytics.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/ConvexHull.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/I18N.CJK.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/I18N.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/I18N.MidEast.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/I18N.Other.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/I18N.Rare.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/I18N.West.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/LZ4.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Newtonsoft.Json.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Behave.Unity.Assets.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Behave.Unity.Runtime.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/protobuf-net.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/RustBuild.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/EasyAntiCheat.Client.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/EasyAntiCheat.Server.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Facepunch.Console.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Facepunch.Input.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Facepunch.Network.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Facepunch.Raknet.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Facepunch.Rcon.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Facepunch.System.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Facepunch.UnityEngine.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Rust.Data.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Rust.Global.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Rust.UI.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Rust.Workshop.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/websocket-sharp.dll into Unity Child Domain
Loading /RustDedicated_Data/Managed/Facepunch.Steamworks.dll into Unity Child Domain
- Completed reload, in  0.050 seconds
OnLevelWasLoaded was found on LeanTween
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
Shader 'Nature/Terrain/Diffuse': dependency 'AddPassShader' shader 'Hidden/TerrainEngine/Splatmap/Diffuse-AddPass' not found
Shader 'Hidden/TerrainEngine/Splatmap/Specular-AddPass': fallback shader 'Hidden/TerrainEngine/Splatmap/Diffuse-AddPass' not found
Shader 'Hidden/TerrainEngine/Splatmap/Standard-AddPass': fallback shader 'Hidden/TerrainEngine/Splatmap/Diffuse-AddPass' not found
UnloadTime: 0.925000 ms
Bootstart Startup
System
Name: 66
OS:   Linux 3.10 unknown 64bit
CPU
Memory: 152915 MB
GPU
API:    NULL 1.0 [1.0]
Memory: 128 MB
SM:     30
Memory
Private:     0 MB
Working Set: 0 MB
Process
Priority: 0
Threads:  0
Memory:   69 MB
Peak:     70 MB
Mono
Collects: 4
Memory:   0 MB
Command Line: "/RustDedicated" "-batchmode" "-nographics" "+server.ip" "0.0.0.0" "+server.port" "12024" "+server.tickrate" "30" "+server.maxplayers" "50" "+server.worldsize" "4000" "+rcon.ip" "0.0.0.0" "+rcon.port" "22025" "+rcon.password" "******" "-logfile" 
server.ip: "0.0.0.0"
server.port: "12024"
server.tickrate: "30"
server.maxplayers: "50"
server.worldsize: "4000"
rcon.ip: "0.0.0.0"
rcon.port: "22025"
server.ip: "0.0.0.0"
server.port: "12024"
server.tickrate: "30"
server.maxplayers: "50"
server.worldsize: "4000"
rcon.ip: "0.0.0.0"
rcon.port: "22025"
UnauthorizedAccessException: Access to the path "/backup/1/my_server_identity/cfg/bans.cfg" is denied.
at System.IO.File.Delete (System.String path) [0x00000] in <filename unknown>:0 
at System.IO.Directory.RecursiveDelete (System.String path) [0x00000] in <filename unknown>:0 
at System.IO.Directory.RecursiveDelete (System.String path) [0x00000] in <filename unknown>:0 
at System.IO.Directory.Delete (System.String path, Boolean recursive) [0x00000] in <filename unknown>:0 
at System.IO.DirectoryInfo.Delete (Boolean recursive) [0x00000] in <filename unknown>:0 
at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo:Delete (bool)
at DirectoryEx.Backup (System.String[VMU] names) [0x00000] in <filename unknown>:0 
at ConVar.Server.backup () [0x00000] in <filename unknown>:0 
at ConsoleGen.<All>m__1EE (.Arg arg) [0x00000] in <filename unknown>:0 
at ConsoleSystem+Run.Internal (.Arg arg, Boolean bWantReply) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Run:Internal(Arg, Boolean)
SystemRealm:Normal(RunOptions, String, String&, Object[VMU])
SystemRealm:Normal(RunOptions, String, Object[VMU])
SystemRealm:Normal(String, Object[VMU])
Bootstrap:Init_Config()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
Server Config Loaded
Running server/my_server_identity/cfg/bans.cfg
Running server/my_server_identity/cfg/users.cfg
Unloading 4 Unused Serialized files (Serialized files now loaded: 72)
UnloadTime: 6.569000 ms
Floating point textures aren't supported on this device (Main Camera (UnityStandardAssets.CinematicEffects.TonemappingColorGrading))
[AmplifyOcclusion] Null graphics device detected. Skipping effect silently.
Unloading 49 unused Assets to reduce memory usage. Loaded Objects now: 53221.
Total: 28.255999 ms (FindLiveObjects: 3.408000 ms CreateObjectMapping: 2.037000 ms MarkObjects: 18.813999 ms  DeleteObjects: 3.996000 ms)
Loading Oxide Core v2.0.3024...
Loading extensions...
Loaded extension CSharp v1.0.3024 by Oxide Team
Loaded extension MySql v1.0.3024 by Oxide Team
Loaded extension Python v1.0.3024 by Oxide Team
Loaded extension SQLite v1.0.3024 by Oxide Team
Loaded extension Unity v1.0.3024 by Oxide Team
Loaded extension Rust v1.0.3024 by Oxide Team
Loaded extension Rust:IO for Oxide v2.9.0 by playrust.io / dcode
Using Covalence provider for game 'Rust'
Loading plugins...
Loading plugins Unity Core v1.0.3024 by Oxide Team
Loading plugins Rust v1.0.3024 by Oxide Team
Loading plugins Rust:IO for Oxide v2.9.0 by playrust.io / dcode
RCon Started on 22025
[3.7s] Procedural Objects
INFO [0.4s] Clutter Topology
INFO [4.2s] Procedural Generation
Destroyed 19 old entities
Spawning 10651 entities
AngryAnt Behave version 2.5 (d859964) - Copyright (C) Emil Johansen - AngryAnt 2015
Loading Complete
Enforcing SpawnPopMap Spawned Initializing 1065Initializing 10 stabFacepunch.Steamworks UnitFacepunch.SteamwFacepunch.SteamwDllNotFoundException: libat (wrapper managed-to-native) SteamNative.Platform/Linux64/Native:SteamInternal_GameServer_Init (uint,uint16,uint16,uintat SteamNative.Platform+Linux64.SteamApi_SteamInternal_GameServer_Init (UInt32 unIP, UInt16 usPort, UInt16 usGamePort, UInt16 usQueryPort, Int32 eServerMode, System.String pchVersionString) [0x00000] in <filenaat SteamNative.SteamApi.SteamInternal_GameServer_Init (UInt32 unIP, UInt16 usPort, UInt16 usGamePort, UInt16 usQueryPort, Int32 eServerMode, System.String pchVersionString) [0x00000] in <filenaat Facepunch.Steamworks.Interop.NativeInterface.InitServer (Facepunch.Steamworks.BaseSteamworks steamworks, UInt32 IpAddress, UInt16 usPort, UInt16 GamePort, UInt16 QueryPort, Int32 eServerMode, System.String pchVersionString) [0x00000] in <filenaat Facepunch.Steamworks.Server..ctor (UInt32 appId, UInt32 IpAddress, UInt16 SteamPort, UInt16 GamePort, UInt16 QueryPort, Boolean Secure, System.String VersionString) [0x00000] in <filenaat Facepunch.Steamworks.Server..ctor (UInt32 appId, UInt32 IpAddress, UInt16 GamePort, UInt16 QueryPort, Boolean Secure, System.String VersionString) [0x00000] in <filenaat Facepunch.Steamworks.Server..ctor (UInt32 appId, UInt32 IpAddress, UInt16 GamePort, Boolean Secure, System.String VersionString) [0x00000] in <filenaat ServerMgr.StartSteamServer () [0x00000] in <filenaat ServerMgr.OpenConnection () [0x00000] in <filenaat Bootstrap+<StartServer>c__IteratorF.MoveNext () [0x00000] in <filenaat UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 `

`Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Update state (0x5) validating, progress: 0.07 (4198973 / 5630150503)
Update state (0x5) validating, progress: 4.25 (239079997 / 5630150503)
Update state (0x5) validating, progress: 13.86 (780145213 / 5630150503)
Update state (0x5) validating, progress: 21.53 (1212158525 / 5630150503)
Update state (0x5) validating, progress: 30.06 (1692530428 / 5630150503)
Update state (0x5) validating, progress: 39.00 (2195846908 / 5630150503)
Update state (0x5) validating, progress: 48.69 (2741106428 / 5630150503)
Update state (0x5) validating, progress: 58.15 (3273969553 / 5630150503)
Update state (0x5) validating, progress: 67.22 (3784747703 / 5630150503)
Update state (0x5) validating, progress: 73.41 (4132874935 / 5630150503)
Update state (0x5) validating, progress: 79.48 (4474710711 / 5630150503)
Update state (0x5) validating, progress: 86.41 (4864780983 / 5630150503)
Update state (0x5) validating, progress: 95.94 (5401651895 / 5630150503)
Success! App '258550' fully installed.`

**Comment by lukespragg** [comment]
Please use our forums or Rust's forums for general server support.

**Comment by cokll** [comment]
@lukespragg http://oxidemod.org/threads/linux-server-will-not-start.23507/
I have already submitted,But still not resolved
