### ISSUE TITLE
ReadObject doesn't create a file if it doesn't exist

### ISSUE THREAD

**Issue by aequasi** [OxideMod/Oxide#103]
https://github.com/OxideMod/Oxide/blob/master/Oxide.Core/DataFileSystem.cs#L103

would be super awesome if it did.

**Comment by aequasi** [comment]
For now, you can do something like the following:

```C#
try
{
    data = Interface.GetMod().DataFileSystem.ReadObject<List<CustomClass>>(datafileName);
}
catch (Exception e)
{
     data = new List<CustomClass>();
    Interface.GetMod().DataFileSystem.WriteObject(datafileName, data);
}
```

**Comment by Feramor** [comment]
This has to be like this Plugin developers should cast it with try structure since we can't construct custom classes with <T> since they may have custom constructers.

**Comment by lukespragg** [comment]
Try the latest build and see how it works out!

https://github.com/OxideMod/Oxide/commit/ca9a791c841f9c7978f628d18600cda26dc7b7f9
