### ISSUE TITLE
Should 'public' accessibility really affect which Fields and Methods get processed in HandleAddedToManager?

### ISSUE THREAD

**Issue by pushedx** [OxideMod/Oxide#1042]
and if so, what is design reasoning?

`foreach (var field in GetType().GetFields(BindingFlags.NonPublic | BindingFlags.Instance))`

`foreach (var method in GetType().GetMethods(BindingFlags.NonPublic | BindingFlags.Instance))`

I was pulling out my hair trying to figure out why my simple code wasn't working, until I finally tracked down the issue.

**Edit:** In CSPlugin, HookMethodAttribute handles public for HookMethodAttribute.

`foreach (var method in types[i].GetMethods(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance))`

**Edit:** In CSharpPlugin, the constructor doesn't handle public for HookMethodAttribute.

`foreach (var method in type.GetMethods(BindingFlags.NonPublic | BindingFlags.Instance))`

**Comment by lukespragg** [comment]
What exactly are you trying to do? CSPlugin is not intended for plugins, CSharpPlugin is.

**Comment by pushedx** [comment]
Hi Luke - here's an example of the results of the issue I'm asking about

```
namespace Oxide.Plugins
{
	[Info("Plugin1", "drew_benton", "1.0")]
	class Plugin1 : RustPlugin
	{
		/// <summary>
		/// The processing of ChatCommandAttribute works for this function because it's non-public.
		/// </summary>
		[ChatCommand("test1")]
		void cmdTest1(BasePlayer player)
		{
			SendReply(player, "test1");
		}

		/// <summary>
		/// The processing of ChatCommandAttribute works for this function because it's non-public.
		/// </summary>
		[ChatCommand("test2")]
		internal void cmdTest2(BasePlayer player)
		{
			SendReply(player, "test2");
		}

		/// <summary>
		/// The processing of ChatCommandAttribute does not work for this function because it's public.
		/// </summary>
		[ChatCommand("test3")]
		public void cmdTest3(BasePlayer player)
		{
			SendReply(player, "test3");
		}
	}
}
```

In game: https://gyazo.com/26adbc291c741e0ede9b51b9d46e4e8f

**Comment by austinv900** [comment]
Agreed. I don't think defining a method as public should effect if it can be called by Interface.Call or plugin.Call

**Comment by lukespragg** [comment]
I'm not sure why it was written this way originally, but right now the // Requires method for referencing a plugin uses the public methods, and .Call uses private methods.
