### ISSUE TITLE
Compilier Auto Download Issue

### ISSUE THREAD

**Issue by austinv900** [OxideMod/Oxide#1043]
Ever since the compiler auto update feature was added I have noticed major performance decreases for startups. It takes an average of 7-8 minutes just to get any console output from the server and for it to finish booting up.

I dunno if this will help or not but maybe making a separate text file during the bintray deployment that contains the SHA1 hash or build number of the compiler that oxide can read and determine if you needs to be downloaded or not.

[https://github.com/OxideMod/Oxide/commit/f1c24aa85de0a6dc2a94630fa2e0ae3fc0597f03](url)

**Comment by lukespragg** [comment]
The compiler is only downloaded once on startup if it is missing.
