### ISSUE TITLE
Can't load any plugin on TheForestDedicatedServer v0.59

### ISSUE THREAD

**Issue by netzulo** [OxideMod/Oxide#1079]
### Step 2: Describe your setup

  * Oxide version _("latest" is not a version)_: **Oxide Core v2.0.0**
  * Game name and version:  **The Forest Dedicated Server v0.59 + Oxide Core v2.0.0** 
  * OS version: **windows 2012 server standard**

### Step 3: Describe the problem

Can't load plugin what compiles successfully on TheForestDedicatedServer

#### Steps to reproduce:

  1. Install TheForestDedicatedServer from steam
  2. Compiles Oxide core v2.0.0 with visual studio
  3. Copy bundles/TheForest to TheForestDedicatedServer_Data on server
  4. Start to create oxide config ( script can be found here : [https://www.netzulo.com/?p=58](https://www.netzulo.com/?p=58) )
  5. Stop script 
  6. Copy plugin file to Oxide/plugins

#### Observed results:

If wrong sintaxis file, server output works and show compile plugin error and start server without this plugin

if success sintaxis file, blank screen server output, and never start

#### Expected results:

1. Any plugin success can be loaded on TheForestDedicatedServer
2. At least... server start

#### Relevant code _(if applicable)_:

  ``` csharp
[Info("CmdPlugin", "Netzulo", 0.1)]
  [Description("Allows to set/send commands to/from server")]
  class CmdPlugin : TheForestPlugin
  {
    #region Configuration

    string PlayerJoined => GetConfig("PlayerJoined", "{name} joined the survivors");
    string PlayerQuit => GetConfig("PlayerQuit", "{name} abandoned the survivors");

    protected override void LoadDefaultConfig()
    {
      try
      {
        Config["PlayerJoined"] = PlayerJoined;
        Config["PlayerQuit"] = PlayerQuit;
        Log("Default config loaded!");
        SaveConfig();
      }
      catch (Exception err)
      {
        Log("Error at init" + err.Message);
      }
    }

    #endregion

    #region Helper Methods
    internal T GetConfig<T>(string name, T defaultValue)
    {
      if (Config[name] == null) return defaultValue;
      return (T)Convert.ChangeType(Config[name], typeof(T));
    }

    internal bool Log(string message, string prefix = "CmdPlugin", string logLevel = "INFO")
    {
      string baseMessage = $"[{prefix}][{logLevel}]: {message}";
      string errMessage = $"[{prefix}][{logLevel}]: ";
      try
      {
        if (message == null || message.Length <= 0)
        {
          //ERROR
          Puts(errMessage);
          return false;
        }
        else
        {
          //OK
          Puts(baseMessage);
          return true;
        }
      }
      catch (Exception err)
      {
        throw new Exception($"[{prefix}][{logLevel}]: {err.Message}");
      }
    }
    #endregion
  ```

### Step 4: Additional information

1. TheForestDedicatedServer release again on 22 april 
2. If you use another "official plugin" and repair file, will find same **blackscreen**

LOGS

14:20 [Error] Exception while patching: CmdPlugin (FileNotFoundException: Could not load file or assembly 'Mono.Cecil.Rocks, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies.)
14:20 [Stacktrace]   at Oxide.Plugins.CompiledAssembly+<>c__DisplayClass20_2.<PatchAssembly>b__0 (System.Object _) [0x00000] in <filename unknown>:0 
14:20 [Error] Exception while calling NextTick callback (NullReferenceException: Object reference not set to an instance of an object)
14:20 [Stacktrace]   at Oxide.Plugins.CompilablePlugin+<>c__DisplayClass6_0.<LoadPlugin>b__0 (Boolean loaded) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.CompiledAssembly.<LoadAssembly>b__19_0 (System.Byte[] rawAssembly) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.CompiledAssembly+<>c__DisplayClass20_3.<PatchAssembly>b__7 () [0x00000] in <filename unknown>:0 
  at Oxide.Core.OxideMod.OnFrame (Single delta) [0x00000] in <filename unknown>:0

**Comment by lukespragg** [comment]
Oxide v2.0.0 is not an official build, please test with an official build from Oxide's Downloads section and provide us the latest logs from oxide/logs.

**Comment by netzulo** [comment]
Downloaded version https://github.com/OxideMod/Oxide/archive/2.0.3218.zip

Same version at server console 

`
-[ES][24/7][NETZULO][Max:100]                                                                                                                       4fps, 5m58s
3/100
                                                                                                                                     Oxide 2.0.0 for 0.11.3.0.0
`

im really sure what im building right server, built clean server 3 times and just applied TheForest Folder on Bundles Folder to server and start it... but got 2.0.0 :(

**Comment by lukespragg** [comment]
That isn't a build, that's the source. You can get the official build from the Releases page or from our homepage under Downloads.

**Comment by netzulo** [comment]
but i want to develop plugins :'( and help with core on TheForest, really obsoleted, so much TODO zone... how i can do then? want to help... :)

PD: tested Official compiled 2.0.3218, works , right version now :(

**Comment by lukespragg** [comment]
It isn't obsolete, just not developed as it was on hold for awhile. :P

I'm looking into it right now though.

**Comment by netzulo** [comment]
ooooooooooooo thank you so much, ill keep my eyes open for commits ! found something interesting ? maybe im not seen... xD

**Comment by lukespragg** [comment]
Looks like you're just missing missing one of the dependency DLLs. I found that the project file just had a path wrong in one area, so try the next build once I release it on the site in a few minutes.

**Comment by netzulo** [comment]
The Boss! Thank you @lukespragg
