### ISSUE TITLE
[Oxide][TheForest] : After 2.0.3222 TheForest source files build Oxide 2.0.0

### ISSUE THREAD

**Issue by netzulo** [OxideMod/Oxide#1081]
#### Steps to reproduce:

+ Got v2.0.322 for Oxide 

  1. Download : [https://github.com/OxideMod/Oxide/releases/download/2.0.3222/Oxide-TheForest.zip](https://github.com/OxideMod/Oxide/releases/download/2.0.3222/Oxide-TheForest.zip)
  2. Copy bundles to server
  3. Start server

+ Got v2.0.0 for Oxide 

  1. Download : [https://github.com/OxideMod/Oxide/archive/2.0.3222.zip](https://github.com/OxideMod/Oxide/archive/2.0.3222.zip)
  2. Generate build with visual studio 2015
  2. Copy bundles/TheForest to server
  3. Start server

#### Observed results:

* Got unexpected version on TheForest server when Build solution on visual studio

#### Expected results:

  * Same result with just **Bundles** and **compiled bundles**

#### Other references:

#1080 #1079

**Comment by lukespragg** [comment]
The build number is attached by our build server. Compiling your own build locally is an indication that you do not have or are not actually using an official build.

**Comment by netzulo** [comment]
@lukespragg ... can't help like this then... im compiling YOUR version... im not touching code... just download and build... and DON't works.. but if i download just theforest bundles compiled by you, then works...

How i can test my code on real server if i can't compile successfully... ? :S

**Comment by lukespragg** [comment]
The build number has nothing to do with it working or not. The files you need would all be under the Bundles version if you are compiling and testing locally.
