### ISSUE TITLE
[TheForest] Don't have OnServerCommand Hook

### ISSUE THREAD

**Issue by netzulo** [OxideMod/Oxide#1091]
### Step 2: Describe your setup

  * Oxide version _("latest" is not a version)_: Oxide-2.0.3242
  * Game name and version: TheForestDedicatedServer v0.59b
  * OS version: Windows 2012 Server / Windows 10

### Step 3: Describe the problem

Type text on server console, don't do anything

#### Steps to reproduce:

  1. Start server
  2. type text on server console
  2.2 type like command server console ( with / )

#### Observed results:

  * Maybe Need hook: **OnServerCommand**
  * You can type on server console, and all existing command on client side will do anything on ServerConsole

#### Expected results:

 * Can handle Event on plugin

#### Relevant code _(if applicable)_:

  ``` csharp
namespace Oxide.Plugins
{
    [Info("TheForestChecker", "Netzulo", 0.1)]
    [Description("Allows to players test server functionality")]
    public class TheForestChecker : TheForestPlugin
    {
        void OnServerCommand()
        {
            //TODO: don't capture anything
        }
    }
}
  ```

#### Other references:

* TheForestServer.cs have Command function
* RustCore.cs have hook name **OnServerCommand**

**Comment by netzulo** [comment]
Ok. I did it this, OnServerCommand without type hookmethod works because have on plugin doing

  ``` csharp
void OnServerCommand(string command)
{
     foreach (var hook in this.hooks)
    {
        PrintWarning($"Hooks-keys: {hook.Key}");
   }
}
  ``` csharp

but i haven't arguments for each method :S .. im on it too

**Comment by netzulo** [comment]
Real hooks on TheForestPlugin Class are...

[TheForestChecker] HOOKNAME: OnPluginLoaded
[TheForestChecker] PARAM: plugin
[TheForestChecker] PARAM-TYPE: Oxide.Core.Plugins.Plugin

[TheForestChecker] HOOKNAME: OnPluginUnloaded
[TheForestChecker] PARAM: plugin
[TheForestChecker] PARAM-TYPE: Oxide.Core.Plugins.Plugin

[TheForestChecker] HOOKNAME: OnPlayerChat
[TheForestChecker] PARAM: evt
[TheForestChecker] PARAM-TYPE: ChatEvent

[TheForestChecker] HOOKNAME: OnServerCommand
[TheForestChecker] PARAM: command
[TheForestChecker] PARAM-TYPE: System.String

**Comment by lukespragg** [comment]
The signature for the OnServerCommand hook already in Oxide for The Forest is:

object OnServerCommand(BoltConnection connection, string command, string data)

**Comment by netzulo** [comment]
ouch, thank you , issue closed then ! :)
