### ISSUE TITLE
SQL security improvements

### ISSUE THREAD

**Issue by Feramor** [OxideMod/Oxide#110]
While building sql strings add a security check for INTO OUTFILE() and Load_FILE().It may risk the webserver's security.

**Comment by Feramor** [comment]
Also I dont know if is there smiliar thing exist with sqlite if exist ppl can write into filesystem :)

**Comment by Feramor** [comment]
Also add mysql and sqlite to  blacklistedNamespaces so force ppl to use Library.

**Comment by lukespragg** [comment]
@Nogrod has made some changes, and should be submitting a PR soon. :)

**Comment by lukespragg** [comment]
Fixed an an upcoming build. :)
