### ISSUE TITLE
Unturned 3.18.11.0 currently not supported?

### ISSUE THREAD

**Issue by Kenterfie** [OxideMod/Oxide#1103]
* Oxide version: 2.0.3271
  * Game name and version: Unturned 3.18.11.0
  * OS version: Windows Server 2012

Problem:
No plugin is loaded and one error at load

```
Failed to load extension Oxide.Core.CSharp (ReflectionTypeLoadException: The cla
sses in the module cannot be loaded.)
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetExportedTypes () [0x00000] in <filename unkno
wn>:0
  at Oxide.Core.Extensions.ExtensionManager.LoadExtension (System.String filenam
e) [0x00000] in <filename unknown>:0
```

**Comment by lukespragg** [comment]
It should be working fine in the latest snapshot (not released yet).

**Comment by Kenterfie** [comment]
What is the reason why the latest snapshot is not released?

**Comment by lukespragg** [comment]
Because we generally do not release new builds right away unless it's for a game we fully support, otherwise we'd wait for a few more changes to be added.
