### ISSUE TITLE
[TheForest] Covalence don't call OnUserChat because player it's null

### ISSUE THREAD

**Issue by netzulo** [OxideMod/Oxide#1105]
### Step 2: Describe your setup

  * Oxide version _("latest" is not a version)_: __v2.0.3248__ ( not updates affected to TheForest at latest )
  * Game name and version: __TheForestDedicatedServerv0.60 and TheForest client v0.60__
  * OS version: __Windows2012Server( server) Windows10 ( client )__

### Step 3: Describe the problem

At try to get hook on plugin, can't on event named **OnUserChat** because variable **iplayer** it's null.

#### Steps to reproduce:

  1. Type text on game chat
  2. Create plugin that extend plugin method named **OnUserChat**
  3. Modify Core to test it

#### Observed results:

After put log on core OnPlayerChat method, i get NULL message on **iplayer** variable, that explains why can't hook named method **OnUserChat**

#### Expected results:

* Can Hook method named **OnUserChat** on new Plugin files

#### Relevant code _(if applicable)_:

Edited core code : [TheForestCore.cs](https://github.com/OxideMod/Oxide/blob/develop/Games/Unity/Oxide.Game.TheForest/TheForestCore.cs#L201)

  ``` csharp
if (iplayer != null) return Interface.Call("OnUserChat", iplayer, evt.Message);
else
{
    Debug.Log($"[CORE][EVENT]: OnPlayerChat NULL IPlayer");
    return null;
}
  ```

#### Other references:

Maybe it's related issue to : #1104 , [[TheForest] Covalence can't ban player by Username, or ID](https://github.com/OxideMod/Oxide/issues/1104)

**Comment by lukespragg** [comment]
Should be resolved in the latest commit and upcoming snapshot.

**Comment by netzulo** [comment]
keep my eyes open, thank you @lukespragg
