### ISSUE TITLE
Forest 0.62 is currently broken

### ISSUE THREAD

**Issue by Kenterfie** [OxideMod/Oxide#1131]
* Oxide version: 2.0.3329
* Game name and version: 0.62
* OS version: Windows Server 2012

#### Problem ####
Game server isnt able to run multiple times
"Bolt Network is already running please shutdown"

#### Steps to reproduce:
Run multiple server on same machine

### Additional information
I have patched the dlls by myself without latest changes from your opj file which work very well, so i think the problem has to do with your latest code changes.

**Comment by lukespragg** [comment]
Oxide does not control which port your server runs on, that's all from The Forest.

**Comment by Kenterfie** [comment]
It happens only with the current oxide release, so i dont think the game itself has something to do with it. Like i said, when i use the old opj file without your latest changes everything is working, when i patch it himself with oxide patcher.

**Comment by lukespragg** [comment]
Could you be more specific about which changes? I had no issues when I initially tested it before release. The error in question though is not from Oxide, and neither is the port handling.

**Comment by Kenterfie** [comment]
Changes from these commit 963a8bae8e6ac0dbb6d1f5f07e5049a602be3a62. Without these changes no error on multiple running instances. I will test it a little bit more, when i have more free time, but i think something is broken. I post some logs later.

**Comment by Kenterfie** [comment]
close - found the reason

**Comment by lukespragg** [comment]
What was the reason?
