### ISSUE TITLE
RemoteConsole Oxide RCON not executing commands

### ISSUE THREAD

**Issue by wledfor2** [OxideMod/Oxide#1155]
### Step 1: Are you in the right place?

  * For bugs or feature requests related to the code _in this repository_, you're in the right place!

### Step 2: Describe your setup

  * Oxide version _("latest" is not a version)_: 2.0.0
  * Game name and version: Rust 2000.147.1
  * OS version: Windows 10 x64

### Step 3: Describe the problem

RemoteConsole fails to execute any command not defined between RemoteConsole.cs lines 129 to 180 (IE: Those that are passed on to Rust's console system). Commands executing using traditional Rust RCON (source rcon, webrcon).

#### Steps to reproduce:

  1. Connect to RemoteConsole using your tool or library of choice.
  2. Run the command "status".
  3. Command is not executed.

#### Observed results:

  * Command is not executed as expected, although it is received by Oxide RCON.

#### Expected results:

  * All commands are executed as expected

#### Relevant code _(if applicable)_:

//Debugging added to make sure the command is received as expected.
        /// &lt;summary&gt;
        /// Handles messages sent from the clients
        /// &lt;/summary&gt;
        /// &lt;param name="e"&gt;&lt;/param&gt;
        private void OnMessage(MessageEventArgs e, WebSocketContext connection)
        {
            var message = RemoteMessage.GetMessage(e.Data);
            message.Message = message.Message.Replace("\"", string.Empty);

            if (message == null || covalence == null || string.IsNullOrEmpty(message.Message))
            {
                Interface.Oxide.LogError($"[Rcon] Failed to process command {(message == null ? "RemoteMessage" : "Covalence")} is null");
                return;
            }

            var msg = message.Message.Split(' ');
            var cmd = msg[0].ToLower();
            var args = msg.Skip(1).ToArray();

            if (Interface.CallHook("OnRconCommand", connection.UserEndPoint.Address, cmd, args) != null) return;

            switch (cmd)
            {
                case "broadcast":
                case "chat.say":
                case "global.say":
                case "say":
                    BroadcastMessage(cmd, args, message.Identifier, connection);
                    break;

                case "global.playerlist":
                case "playerlist":
                    PlayerListCommand(cmd, args, message.Identifier, connection);
                    break;

                case "hostname":
                case "server.hostname":
                    HostnameCommand(cmd, args, message.Identifier, connection);
                    break;

                case "global.kick":
                case "kick":
                    KickCommand(cmd, args, message.Identifier, connection);
                    break;

                case "save":
                case "server.save":
                    covalence.Server.Save();
                    SendMessage(connection, "Server saved", message.Identifier);
                    break;

                case "ban":
                case "banid":
                case "global.ban":
                case "global.banid":
                    BanCommand(cmd, args, message.Identifier, connection);
                    break;

                case "global.unban":
                case "unban":
                    UnbanCommand(cmd, args, message.Identifier, connection);
                    break;

                case "server.version":
                case "version":
                    SendMessage(connection, $"{covalence.Game} {covalence.Server.Version} - Protocol {covalence.Server.Protocol} with Oxide v{OxideMod.Version}", message.Identifier);
                    break;

                case "global.teleport":
                case "global.teleportpos":
                case "teleport":
                case "teleportpos":
                    TeleportCommand(cmd, args, message.Identifier, connection);
                    break;

                default:
                    Interface.Oxide.LogInfo($"Passing command {cmd} on to Rust.");
                    covalence.Server.Command(cmd, args);
                    break;
            }
        }

**Comment by lukespragg** [comment]
This is as designed right now.

**Comment by wledfor2** [comment]
I see, that's unfortunate. It reduces usefulness significantly. I guess I'll switch my project to Rust's webrcon.

**Comment by lukespragg** [comment]
The commands will still execute as I mentioned, you just may not see a reply in the console. Last time I tested though most commands still sent a reply back, it just depends on how the reply is sent.

**Comment by wledfor2** [comment]
Thanks for the clarification.
