### ISSUE TITLE
Plugin compile error when trying to access JsonSerializerSettings

### ISSUE THREAD

**Issue by Skippeh** [OxideMod/Oxide#1158]
### Setup

  * Oxide version: 2.0.3382
  * Game name and version: Rust v 1090 (2001.147.1)
  * OS version: Windows 10 and Windows Server 2012 R2 (tested on both)

#### Steps to reproduce:

  1. Run the code below as a plugin.

#### Observed results:

Compile time error: ``Error while compiling: Test.cs(13,20): error CS0023: The `.' operator cannot be applied to operand of type `Newtonsoft.Json.JsonSerializerSettings'``

#### Expected results:

Expected the code to compile normally without any errors.

#### Code to reproduce error:

``` csharp
using System;
using Newtonsoft.Json;

namespace Oxide.Plugins
{
    [Info("Test", "", "1.0.0")]
    [Description("")]
    public class Test : RustPlugin
    {
        private void Init()
        {
            Config.Settings.ToString();
        }
    }
}
```

**Comment by lukespragg** [comment]
http://oxidemod.org/threads/the-operator-cannot-be-applied-to-operand-of-type-newtonsoft-json-jsonserializersettings.26554/page-4#post-340450 ;)
