### ISSUE TITLE
Reloading plugins does not reset static values

### ISSUE THREAD

**Issue by Skippeh** [OxideMod/Oxide#1160]
### Setup

  * Oxide version: 2.0.3384
  * Game name and version: Rust v1090 (2001.147.1)
  * OS version: Windows 10

#### Steps to reproduce:

  1. Load plugin
  2. Reload plugin using oxide.reload or unload/load

#### Observed results:

Static variables keep their old values.

#### Expected results:

Expected everything to be reset to their initial state.

#### Relevant code:

  ``` csharp
using System;

namespace Oxide.Plugins
{
	[Info("Test", "", "1.0.0")]
	[Description("")]
	public class Test : RustPlugin
	{
		public static int StaticVariable = 0;

		private void Init()
		{
			Puts(StaticVariable++.ToString()); // This will put 1, 2, 3, 4, etc in the console on every reload. Recompiling resets it to 0.
		}
	}
}
  ```

**Comment by lukespragg** [comment]
Static values persist, which is why you should avoid using them in most cases for plugins unless you really want it to persist.
