### ISSUE TITLE
Automatic configuration reloading on changes

### ISSUE THREAD

**Issue by Feramor** [OxideMod/Oxide#117]
Hello, it would be good if we had this with using FileSystemWatcher.So ppl dont need to restart or reload plugin :)

**Comment by lukespragg** [comment]
A hook wouldn't be used for it, the FSWatcher would just need to watch the config dir as well.

**Comment by Feramor** [comment]
Can't we do like LoadDefaultConfig() hook?

**Comment by lukespragg** [comment]
Why is a hook needed at all? The best solution to me is just monitoring the configs just like how we do with the plugins themselves.

**Comment by Feramor** [comment]
Plugin should now something changed.Maybe he do some operations @ Init

**Comment by lukespragg** [comment]
So we've thought about this more recently. We don't really see an ideal way to handle this without tracking every config file (some plugins have multiple) to link it to a plugin. A hook could be added without the tracking, but then you'd have to call that hook on every plugin that is loaded every time one config file changes.

Even if we added changes to make the filesystem watch for changes, there are concerns that this would cause more harm than good as users tend to safe frequently while editing, so any invalid changes could spur the plugin to reset the config to default.
