### ISSUE TITLE
[The Forest] Server Launch Failure 

### ISSUE THREAD

**Issue by Br0ly** [OxideMod/Oxide#1223]
* Oxide version: Core 2.0.3596
  * Game name and version: The Forest 0.69
  * OS version: Windows Server 2016

### Problem
Server does not reach full initialization.
The Forest Dedicated Server just stops doing anything past the "The Forest Server is Vac Secure!" (If enabled otherwise stops at after "Connected to Steam Successfully"
Is still responding in tasks but memory usage does not change, still shows process activity.
Logs are clean. No errors.

#### Reproduction
  1. Install Oxide into Server Directory
  2. Run Server Application

**Comment by lukespragg** [comment]
I noticed that once, but can't reproduce it anymore. Oxide doesn't control how your server starts though, so I suspect the issue lies with the game itself, perhaps with save loading.

**Comment by Br0ly** [comment]
Test without Oxide loads fully with no issues.

Able to connect and use server.

**Comment by netzulo** [comment]
im testing 2 days ago... can't start official steam server throught , but still i don't know why , im on it too @lukespragg

**Comment by lukespragg** [comment]
I'll take a look in a bit. Unsure why it's doing that.
