### ISSUE TITLE
Warning console related to oxide i think

### ISSUE THREAD

**Issue by Owned67** [OxideMod/Oxide#1224]
Hello,

if not related, i post on forum, no worrie, sorry... it's not critical i think?

Ignored unnecessary '// Reference: Newtonsoft.Json' in plugin 'AntiOfflineRaid'
Ignored unnecessary '// Reference: Newtonsoft.Json' in plugin 'EntityOwner'

### Step 2: Describe your setup

  * Oxide version : 2.0.3600 for 1789 (2024.152.1)
  * Game name and version: Rust v2024 (Windows, Dedicated, Protocol 17)
  * OS version: Windows 10 Pro x64

#### Steps to reproduce:

  1. install plugin 

#### Observed results:

>  Ignored unnecessary '// Reference: Newtonsoft.Json' in plugin 'AntiOfflineRaid'
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
Ignored unnecessary '// Reference: Newtonsoft.Json' in plugin 'EntityOwner'

**Comment by lukespragg** [comment]
Those are normal, it means that those plugins are trying to reference a DLL that is referenced by default in Oxide.
