### ISSUE TITLE
Doesn't compile from source, skipped projects, build hangs

### ISSUE THREAD

**Issue by generationtech** [OxideMod/Oxide#1225]
This is a carry-over from Oxide forums discussion:
[http://oxidemod.org/threads/compiling-oxide-from-source.27635](url)

### Step 2: Describe your setup

  * Oxide version 2.0.3600 and current development branch
  * Game name and version: Rust, buildid 2214178
  * OS version: Server 2012
  * Build environment: MSVC 2017 release version

### Step 3: Describe the problem

Downloading and attempting to build source for master or development branch does not work. 

* Upon opening project in MSVC 2017, there is error dialogue box:
```
Problem signature:
  Problem Event Name:    Dev11NonFatalError
  AppName:    devenv.exe
  AppVer:    15.0.27004.2005
  AppStamp:    59e69397
  AsmAndModName:    Microsoft.VisualStudio.Validation
  AsmVer:    15.3.15.16354
  ModStamp:    cdeef569
  MethodDef:    29
  Offset:    58
  ExceptionType:    System.ArgumentException
  Component:    CPS
  OS Version:    6.3.9600.2.0.0.272.7
  Locale ID:    1033

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```
* And second error dialogue box (graphic only):
```
dimensionValueMap must contain one value
```

* Auto building results in:

```
1>------ Skipped Build: Project: References ------
1> 
2>------ Skipped Build: Project: Core ------
2> 
3>------ Skipped Build: Project: CSharp ------
3> 
4>------ Skipped Build: Project: SQLite ------
4> 
5>------ Skipped Build: Project: Lua ------
5> 
6>------ Skipped Build: Project: MySql ------
6> 
7>------ Skipped Build: Project: Unity (Extensions\Unity) ------
7> 
8>------ Skipped Build: Project: JavaScript ------
8> 
9>------ Skipped Build: Project: Python ------
9> 
10>------ Skipped Build: Project: Blackwake ------
10> 
11>------ Skipped Build: Project: Hurtworld ------
11> 
12>------ Skipped Build: Project: MedievalEngineers ------
12> 
13>------ Skipped Build: Project: ReignOfKings ------
13> 
14>------ Skipped Build: Project: Rust ------
14> 
15>------ Skipped Build: Project: SavageLands ------
15> 
16>------ Skipped Build: Project: SpaceEngineers ------
16> 
17>------ Skipped Build: Project: TheForest ------
17> 
========== Build: 0 succeeded or up-to-date, 0 failed, 17 skipped ==========
```

#### Steps to reproduce:

  1. Download source
  2. From within MSVC 2017, choosing either "Debug" or "Release" target is same result
  3. Attempt automatic (normal style) of build

#### Observed results:

  * Build never completes for any game

#### Expected results:

  * Build complete as before by just downloading source and compile without changing anything other than "Debug" or "Release" target in MSVC 2017

#### Relevant code _(if applicable)_:
When building any game, the process will hang here
  ``` Done building project "Lua.csproj".
Lua -> C:\GitHub\serverside\Oxide\Extensions\Oxide.Lua\bin\Release\net40\Oxide.Lua.dll
LuaExtension.cs(31,29,31,44): warning CS0114: 'LuaExtension.IsCoreExtension' hides inherited member 'Extension.IsCoreExtension'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.
Lua -> C:\GitHub\serverside\Oxide\Extensions\Oxide.Lua\bin\Release\net45\Oxide.Lua.dll
Lua -> C:\GitHub\serverside\Oxide\Extensions\Oxide.Lua\bin\Release\net461\Oxide.Lua.dll
Done building project "Lua.csproj".
Successfully created package 'C:\GitHub\serverside\Oxide\Extensions\Oxide.Lua\bin\Release\Oxide.Lua.2.0.0.nupkg'.
------ Build started: Project: Rust, Configuration: Release Any CPU ------
  ```

### Step 4: Additional information

As mentioned by Frenk92 in the forums thread, replacing this line in rust.csproj
```
<Exec Command="powershell -ExecutionPolicy Unrestricted $(SolutionDir)Steam.ps1 -project $(AssemblyName) -dotnet $(TargetFramework) -appid $(SteamAppId) -branch $(SteamBranch) -managed $(ManagedDir)" />
```
With this
```
<Exec Command="powershell -ExecutionPolicy Bypass $(SolutionDir)Steam.ps1 -project $(AssemblyName) -dotnet $(TargetFramework) -appid $(SteamAppId) -branch $(SteamBranch) -managed $(ManagedDir)" />
```
Allows a "batch build" where only OxideMod projects and the Rust game are selected to successfully build and be installed

**Comment by generationtech** [comment]
I just compiled with update development branch ` fdc8409` and by using the batch build, all projects compile successfully for every game, for release and debug targets.

Still have the 2 dialogue box errors when opening MSVC by double-clicking the Oxide.sln file. I once open, I close the solution and re-open it, I only get the 2nd dialogue box error `dimensionValueMap must contain one value`

**Comment by lukespragg** [comment]
Yeah, that dimensionValueMap seems to be the main issue now, just unsure how to reproduce it myself.

**Comment by Owned67** [comment]
> I just compiled with updated development branch fdc8409 and by using the batch build, all projects compile successfully for every game, for release and debug targets.

How? i get error (invalid/incompatible project...) with .sln file...

**Comment by lukespragg** [comment]
@Owned67, what is the specific version that Visual Studio 2017 shows?

**Comment by generationtech** [comment]
I bet he's on 2015 version. I'm using the released version Luke, not the devel MSVC like you and mine works fine.

**Comment by lukespragg** [comment]
Yeah, only way you'd see anything about an invalid project is if you're not on any 2017 version, only older versions such as 2015.

**Comment by Owned67** [comment]
Version 2017:

> Non pris en charge
Cette version de Visual Studio ne parvient pas à ouvrir les projets suivants. Les types de projets ne sont peut-être pas installés ou cette version de Visual Studio ne les prend peut-être pas en charge.
Pour plus d'informations sur l'activation de ces types de projets ou sur la migration de vos actifs, consultez les détails dans le "Rapport de migration" qui s'affiche lorsque vous cliquez sur OK.

Core, "B:\Oxide-master\Oxide.Core\Core.csproj"
Modifications non fonctionnelles requises
Des modifications non fonctionnelles seront automatiquement apportées par Visual Studio aux projets suivants, afin de rendre possible leur ouverture dans Visual Studio 2015, Visual Studio 2013, Visual Studio 2012 et Visual Studio 2010 SP1. Ces modifications n'auront aucune incidence sur le comportement des projets.

Oxide, "B:\Oxide-master\Oxide.sln"


version 2015:

> B:\Oxide-master\Games\Oxide.Blackwake\Blackwake.csproj : error  : L'espace de noms XML par défaut du projet doit être l'espace de noms XML MSBuild. Si le projet a été créé au format MSBuild 2003, ajoutez xmlns="http://schemas.microsoft.com/developer/msbuild/2003" à l'élément <Project>. S'il a été créé dans des formats anciens comme 1.0 ou 1.2, convertissez-le au format MSBuild 2003.  B:\Oxide-master\Games\Oxide.Blackwake\Blackwake.csproj

B:\Oxide-master\Games\Oxide.MedievalEngineers\MedievalEngineers.csproj : error  : L'espace de noms XML par défaut du projet doit être l'espace de noms XML MSBuild. Si le projet a été créé au format MSBuild 2003, ajoutez xmlns="http://schemas.microsoft.com/developer/msbuild/2003" à l'élément <Project>. S'il a été créé dans des formats anciens comme 1.0 ou 1.2, convertissez-le au format MSBuild 2003.  B:\Oxide-master\Games\Oxide.MedievalEngineers\MedievalEngineers.csproj

**Comment by lukespragg** [comment]
@Owned67, okay, but what is the exact version you are using?

**Comment by Owned67** [comment]
MVS 2015 Pro 14.0.25431.01 Update 3 (Net framework 4.7.02556)

MVS 2017 Pro 15.4.1 (Net framework 4.7.02556)

**Comment by generationtech** [comment]
But the first error message you posted claiming to be from 2017 version seems to indicate it was being loaded from 2015 version:

Translated?
[https://translate.google.com/?um=1&ie=UTF-8&hl=en&client=tw-ob#auto/en/Modifications%20non%20fonctionnelles%20requises%0ADes%20modifications%20non%20fonctionnelles%20seront%20automatiquement%20apport%C3%A9es%20par%20Visual%20Studio%20aux%20projets%20suivants%2C%20afin%20de%20rendre%20possible%20leur%20ouverture%20dans%20Visual%20Studio%202015%2C%20Visual%20Studio%202013%2C%20Visual%20Studio%202012%20et%20Visual%20Studio%202010%20SP1.%20Ces%20modifications%20n%27auront%20aucune%20incidence%20sur%20le%20comportement%20des%20projets.](url)

**Comment by lukespragg** [comment]
Hmmm, are you using Pro or Enterprise too @generationtech? I'm on the Community version.

**Comment by Owned67** [comment]
i can try with community version, no worrie, just tell me requirement for installation ?

**Comment by generationtech** [comment]
I'm on Enterprise version, 15.4.1

**Comment by lukespragg** [comment]
Seeing a theme here... :P

**Comment by generationtech** [comment]
Ok theme for my original issues or @Owned67 's?

**Comment by lukespragg** [comment]
Sorry, "pattern" would be a better word to use for it.
1 x Community and working
1 x Pro and not working
2 x Enterprise and not working

**Comment by Owned67** [comment]
So ok i try with community version 2017, i'l back after.

**Comment by generationtech** [comment]
OK, I will try with Community. I get Enterprise free from access to DreamSpark.
But mine _is working_ *. I don't have anything like @Owned67 issue and never got any kind of incompatibility message when first opening a freshly unzipped OxideMod source tree

**Comment by lukespragg** [comment]
@generationtech, the only issue you have that everyone else has other than me (only Community user that I know of) is the dimensionValueMap error on start though.

**Comment by Owned67** [comment]
@lukespragg i need to install what with community edition ? SDK ? Net native ? can you give more details please

**Comment by lukespragg** [comment]
VS should be all you need, but if you see anything else that you might see relevant it wouldn't hurt.

**Comment by Owned67** [comment]
I'm noob for this... ^^ ok I'l install by defaut

**Comment by Owned67** [comment]
I get same error

> Non pris en charge
Cette version de Visual Studio ne parvient pas à ouvrir les projets suivants. Les types de projets ne sont peut-être pas installés ou cette version de Visual Studio ne les prend peut-être pas en charge. 
Pour plus d'informations sur l'activation de ces types de projets ou sur la migration de vos actifs, consultez les détails dans le "Rapport de migration" qui s'affiche lorsque vous cliquez sur OK.
	 - Core, "B:\Oxide-master\Oxide.Core\Core.csproj"


Modifications non fonctionnelles requises
Des modifications non fonctionnelles seront automatiquement apportées par Visual Studio aux projets suivants, afin de rendre possible leur ouverture dans Visual Studio 2015, Visual Studio 2013, Visual Studio 2012 et Visual Studio 2010 SP1. Ces modifications n'auront aucune incidence sur le comportement des projets.
	 - Oxide, "B:\Oxide-master\Oxide.sln"


15.4.1

**Comment by lukespragg** [comment]
Still sounds like you're somehow opening it in Visual Studio 2015 @Owned67. Try manually opening Visual Studio 2017 and then opening the .sln or .csproj from there.

**Comment by generationtech** [comment]
I don't understand why that message reference version 2015 and not 2017. It specifically translates to:

> Non supported
This version of Visual Studio fails to open the following projects. Project types may not be installed or this version of Visual Studio may not support them.
For more information about enabling these types of projects or migrating your assets, see the details in the "Migration Report" that appears when you click OK.

and here

> Non-functional changes required
Non-functional edits will automatically be made by Visual Studio to the following projects to make them open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. These changes will not affect the behavior of the projects.

Those error messages say _nothing_ about version 2017

**Comment by lukespragg** [comment]
@generationtech, it sounds like @Owned67 has VS 2015 as the default instead of VS 2017, so when clicking on it to open it it opens VS 2015 instead.

**Comment by Owned67** [comment]
I don't double clic, open with... and select MVS 2017...

> Try manually opening Visual Studio 2017 and then opening the .sln or .csproj from there.

same error

**Comment by lukespragg** [comment]
Could you show a screenshot of the entire screen with it open else a gif of your steps @Owned67? www.gyazo.com would work great for both else the built-in stuff that VS 2017 has.

**Comment by Owned67** [comment]
http://zupimages.net/up/17/42/shps.gif

**Comment by lukespragg** [comment]
@Owned67 https://developercommunity.visualstudio.com/content/problem/16409/project-created-in-visual-studio-2017-wont-load-af.html

**Comment by Owned67** [comment]
It's latest version @lukespragg....

**Comment by lukespragg** [comment]
@Owned67, I realize that, just pointing out something that may be the cause on your end. What you are experiencing isn't an issue with the project files, it appears to be either a corrupt install or an isolated bug with VS 2017.

**Comment by generationtech** [comment]
Lol, I have a new one. I've been rate-limited during my build tests...

```
Determining latest release of DepotDownloader
Invoke-WebRequest : {"message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But
here's the good news: Authenticated requests get a higher rate limit. Check
out the documentation for more details.)","documentation_url":"https://develope
r.github.com/v3/#rate-limiting"}
At C:\GitHub\vips\serverside\Oxide\Steam.ps1:46 char:14
+ ...    $json = (Invoke-WebRequest "https://api.github.com/repos/SteamRE/D ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by lukespragg** [comment]
That's a lot of testing @generationtech. :P

I'll probably add a hidden .githublogin file for handling logins for this if available.

**Comment by generationtech** [comment]
Took one for the testing team, I guess.

**Comment by lukespragg** [comment]
Normally I don't think you'd hit 60 builds in an hour @generationtech though, but wouldn't hurt.

**Comment by Owned67** [comment]
I have reinstalled MVS 2017 and same, fucking microsoft...... Good Luck @generationtech

**Comment by lukespragg** [comment]
@Owned67, from what I've been seeing, your install is possibly missing an SDK. When installing Visual Studio 2017, did you see anything regarding .NET Core or other SDKs?

**Comment by generationtech** [comment]
Clean install of MSVC 2017 Community Edition 15.4.1 on a different existing virtual machine (Server 2012 R2 Standard Edition) with very little applications already installed, mostly used to support a Rust staging server.

Result:

Still get errors on loading -
`Problem signature:
  Problem Event Name:    Dev11NonFatalError
  AppName:    devenv.exe`
and 
`dimensionValueMap must contain one value`

I can build he OxideMod parts from the batch build manner, but when I check Rust, I get this

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'UnityEngine' could not be found (are you missing a using directive or an assembly reference?)	Rust	C:\Oxide\Games\Oxide.Rust\Libraries\Command.cs	8	Active`

**Comment by lukespragg** [comment]
@generationtech, did you look at the SDK information I linked and try it?

The last error is from the Steam script not running and downloading all of the dependency DLLs for the game needed to compile the extension.

**Comment by generationtech** [comment]
I glanced at the SDK info but thought that was for @Owned67 problem of incomplete install and not for me

Regarding Steam, I thought so too, but I have PS5 on that vm and in the `\games\dependencies\oxide.rust\rustdedicated_data\managed` there are files, so I would guess they were downloaded OK.

**Comment by lukespragg** [comment]
Is the UnityEngine.dll in there to @generationtech?

**Comment by generationtech** [comment]
Yes
[https://imgur.com/8OJxuxr](url)

**Comment by Owned67** [comment]
@lukespragg i need select all or? have you more details for me please?
http://zupimages.net/up/17/42/733j.gif

or I'l install dotnet-sdk?

**Comment by lukespragg** [comment]
I'd suggest doing all of the .NET SDK packs, especially those that we use: 3.5, 4.0, 4.5, and 4.6.1 right now.

**Comment by Owned67** [comment]
Non pris en charge
Cette version de Visual Studio ne parvient pas à ouvrir les projets suivants. Les types de projets ne sont peut-être pas installés ou cette version de Visual Studio ne les prend peut-être pas en charge. 
Pour plus d'informations sur l'activation de ces types de projets ou sur la migration de vos actifs, consultez les détails dans le "Rapport de migration" qui s'affiche lorsque vous cliquez sur OK.
	 - Tests, "B:\Oxide\Oxide.Tests\Tests.csproj"

Aucune modification requise
Ces projets peuvent être ouverts dans Visual Studio 2015, Visual Studio 2013, Visual Studio 2012 et Visual Studio 2010 SP1 sans les modifier.
	 - Core, "B:\Oxide\Oxide.Core\Core.csproj"
	 - References, "B:\Oxide\Oxide.References\References.csproj"
	 - CSharp, "B:\Oxide\Extensions\Oxide.CSharp\CSharp.csproj"
	 - JavaScript, "B:\Oxide\Extensions\Oxide.JavaScript\JavaScript.csproj"
	 - Lua, "B:\Oxide\Extensions\Oxide.Lua\Lua.csproj"
	 - MySql, "B:\Oxide\Extensions\Oxide.MySql\MySql.csproj"
	 - Python, "B:\Oxide\Extensions\Oxide.Python\Python.csproj"
	 - SQLite, "B:\Oxide\Extensions\Oxide.SQLite\SQLite.csproj"
	 - Unity, "B:\Oxide\Extensions\Oxide.Unity\Unity.csproj"
	 - Blackwake, "B:\Oxide\Games\Oxide.Blackwake\Blackwake.csproj"
	 - Blockstorm, "B:\Oxide\Games\Unity\Oxide.Game.Blockstorm\Blockstorm.csproj"
	 - FromTheDepths, "B:\Oxide\Games\Unity\Oxide.Game.FromTheDepths\FromTheDepths.csproj"
	 - FortressCraft, "B:\Oxide\Games\Unity\Oxide.Game.FortressCraft\FortressCraft.csproj"
	 - GangBeasts, "B:\Oxide\Games\Unity\Oxide.Game.GangBeasts\GangBeasts.csproj"
	 - Hurtworld, "B:\Oxide\Games\Oxide.Hurtworld\Hurtworld.csproj"
	 - InterstellarRift, "B:\Oxide\Games\Other\Oxide.Game.InterstellarRift\InterstellarRift.csproj"
	 - MedievalEngineers, "B:\Oxide\Games\Oxide.MedievalEngineers\MedievalEngineers.csproj"
	 - Nomad, "B:\Oxide\Games\Other\Oxide.Game.Nomad\Nomad.csproj"
	 - PlanetExplorers, "B:\Oxide\Games\Unity\Oxide.Game.PlanetExplorers\PlanetExplorers.csproj"
	 - ReignOfKings, "B:\Oxide\Games\Oxide.ReignOfKings\ReignOfKings.csproj"
	 - Rust, "B:\Oxide\Games\Oxide.Rust\Rust.csproj"
	 - RustLegacy, "B:\Oxide\Games\Unity\Oxide.Game.RustLegacy\RustLegacy.csproj"
	 - SavageLands, "B:\Oxide\Games\Oxide.SavageLands\SavageLands.csproj"
	 - SevenDays, "B:\Oxide\Games\Unity\Oxide.Game.SevenDays\SevenDays.csproj"
	 - SpaceEngineers, "B:\Oxide\Games\Oxide.SpaceEngineers\SpaceEngineers.csproj"
	 - Terraria, "B:\Oxide\Games\Other\Oxide.Game.Terraria\Terraria.csproj"
	 - TheForest, "B:\Oxide\Games\Oxide.TheForest\TheForest.csproj"
	 - Unturned, "B:\Oxide\Games\Unity\Oxide.Game.Unturned\Unturned.csproj"
	 - Extensions, "Extensions"
	 - Games, "Games"
	 - Other, "Other"
	 - Unity, "Unity"
	 - VRage, "VRage"
	 - Oxide, "B:\Oxide\Oxide.sln"

I have installed all Net SDK but i get: SDK microsoft.NET.sdk was not found in Core.csproj

**Comment by lukespragg** [comment]
We may have found out the cause, should have some fixes soon. VS 2017 doesn't like parts of the remaining older project files, but I'll be replacing those soon anyway. 

@Mughisi found that if you replace:
<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />

With:
<Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

It seems to solve most of the issues. This is only for the projects that haven't been converted yet, though unsure why everyone is having that issue other than me and the build server.

**Comment by Owned67** [comment]
Thanks, but i don't have more time for test... sorry, good luck.

**Comment by generationtech** [comment]
Yeah, my attempt at a Community Edition was total fail. At least my primary dev env on Enterprise Edition works. I don't think I can be much more help @lukespragg right now. When you get those fixes in place soon I'll try again. I am able to build the sources acceptably for now, so I'm ok*

**Comment by lukespragg** [comment]
All of the projects are now using the new format, so please let me know if you still have the issues when opening or building.

**Comment by Vlad-00003** [comment]
https://pastebin.com/raw/hT1g94PQ

**Comment by Vlad-00003** [comment]
Also - one of the ppl i'm contacting with has the same problem. Also latest version.
Any attempt to just build the project - VS just skips every project. Batch build works just fine - it compiles everything with no errors.

**Comment by generationtech** [comment]
Back again. I download the current development branch and had these errors when compiling it:

1. The "Dev11NonFatalError" is still there when opening
2. The "dimensionValueMap must contain one value" is still there when opening
3. I started a Release build normally by right-clicking on the top of Solution Explorer:
- About 3/4 of the way through I guess "Oxide Patcher" crashed because I got a **multiple** Windows error dialogue box about it
````
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	OxidePatcher.exe
  Problem Signature 02:	1.0.235.0
  Problem Signature 03:	59e78b17
  Problem Signature 04:	OxidePatcher
  Problem Signature 05:	1.0.235.0
  Problem Signature 06:	59e78b17
  Problem Signature 07:	1ae
  Problem Signature 08:	21
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	5f25
  Additional Information 4:	5f2531ae070278f893fa99352dadd49e
````
- At the end of the failed compile there were 2 errors 
````
CS0117	'VoiceCom' does not contain a definition for 'playerList'	RustLegacy	C:\GitHub\vips\serverside\Oxide\Games\Oxide.RustLegacy\RustLegacyCore.cs	267	Active
````
and
````
CS0122	'MyEntityStat.m_maxValue' is inaccessible due to its protection level	SpaceEngineers	C:\GitHub\vips\serverside\Oxide\Games\Oxide.SpaceEngineers\Libraries\Covalence\SpaceEngineersPlayer.cs	165	Active

````
I re-ran the build (after cleaning it) and got even more errors. Rebooted the vm too. Stuff like this:
````
CS1061	'PlayerSession' does not contain a definition for 'IPlayer' and no extension method 'IPlayer' accepting a first argument of type 'PlayerSession' could be found (are you missing a using directive or an assembly reference?)	Hurtworld	C:\GitHub\vips\serverside\Oxide\Games\Oxide.Hurtworld\HurtworldHooks.cs	103	Active
````

If I do a Batch Build and just select all the OxideMod non-game projects, it builds successfully.

**_When I go back and add Rust to the Batch Build, it succeeds._**

If I try a 3rd time to Batch Build by select-all and get all kinds of errors....

**Comment by generationtech** [comment]
Update: I went right back through the build steps **that worked**, and **they failed** the 2nd time. Sheesh

**Comment by generationtech** [comment]
I tried the same thing about an hour later and it worked. I dunno what's going on. I didn't test more than about 5 times originally today, so I can't see how it throttled something being download. Overall it seems to me the newer style of building OxideMod still has issues and is a lot more complicated than before.

Also, when I compile, OxideMod reports in as version 2.0.0 from the Rust server console.

If I can help further with testing or information, please let me know. I'm happy to do it.

**Comment by lukespragg** [comment]
The compile errors are from each game's DLLs not being patched when you build it, likely from the errors you got with the patcher.

The 2.0.0 version is the local version as no build number is injected.

**Comment by generationtech** [comment]
Regarding the version number, didn't the previous style of building OxideMod (MSVC2015) result in current versions numbers being compiled in? Or was that just the master branch. Because I know I've been compiling source for over a year with version numbers showing

**Comment by lukespragg** [comment]
No, it's always only build from our build server. Compiling locally has no build number.

**Comment by Vlad-00003** [comment]
Oook.... I've downloaded the latest version and... no errors on startup!
Gonna see how it would builds.
---------
Rust still failes to builds - it's looking for a release version of core, but the core is being compilated as the debug....

**Comment by Vlad-00003** [comment]
Batch build works just fine

**Comment by lukespragg** [comment]
Any of you still having this issue with the split repos?

**Comment by Vlad-00003** [comment]
nope. everything is fine on my side. =)
