### ISSUE TITLE
Not loading extensions mainly python

### ISSUE THREAD

**Issue by 123hotdog1100** [OxideMod/Oxide#1230]
* Oxide version _("latest" is not a version)_:Oxide 2
  * Game name and version: Rust 182
  * OS version: Windows server 2016

The server seems to start normally but always closes.
I have attached the logs
[oxide_2017-10-23.txt](https://github.com/OxideMod/Oxide/files/1407394/oxide_2017-10-23.txt)

**Comment by lukespragg** [comment]
You're using version of the Python extension from about half a year ago, updating would fix it.
