### ISSUE TITLE
Mono not accepting ECC SSL certs automatically 

### ISSUE THREAD

**Issue by gartia** [OxideMod/Oxide#1250]
The problem is with "webrequest.Enqueue" itself.  When you call a domain with a ECC cert it returns code 0 with this error
`Error getting response stream (Write: The authentication or decryption has failed.): SendFailure`

I am not the most advanced in stuff like this or anything like that, but from what i gather adding this before... maybe after i couldn't test it myself
`ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;`
Should pass the check now i know plugins can't access System.net thats why i was thinking maybe adding a bool to webrequest.Enqueue where it forces the ssl cert to be approved.  

On a side note of what i i was using as a work aroaund because webrequest wouldn't work with my site because of the certificates i am not sure if this gives any usefulness at all.
```
WWWForm PostData = new WWWForm();
WWW www = new WWW(URL, PostData, headers =new Dictionary<string, string>);
```

**Comment by lukespragg** [comment]
See https://github.com/OxideMod/Oxide/issues/947#issuecomment-265286995.

**Comment by gartia** [comment]
Damn... i feel like quiet a bit of people use ECC certs too... though like the bottom of my post thats my work around for web requests :P
