### ISSUE TITLE
Hook OnPlayerInteract not working

### ISSUE THREAD

**Issue by Mordeus** [OxideMod/Oxide#1252]
Oxide build 3720
Testing my new plugin and OnPlayerInteract doesn't work with the new build. I am getting a console error when interacting with items:
![error](https://user-images.githubusercontent.com/27739678/32637290-90ea60b0-c57e-11e7-9191-1f5e33f0ebfb.png)
It worked for me with the settings I have screens of below, I noticed you changed the return behavior? It was working for me with Continue. 
![onplayerinteract1](https://user-images.githubusercontent.com/27739678/32637542-fccaddc2-c57f-11e7-8d93-fc6738f22ba0.png)
![onplayerinteract2](https://user-images.githubusercontent.com/27739678/32637557-23dac5a8-c580-11e7-90dd-567f8af675a0.png)

**Comment by lukespragg** [comment]
The error is just an IL error, not an issue with the return. I'll fix it shortly.

**Comment by lukespragg** [comment]
Should be fixed in the next snapshot, thanks.

**Comment by Mordeus** [comment]
I downloaded your .opj file and injected and it is working just fine, just thought I would let you know..
Thanks Wulf!!
