### ISSUE TITLE
Version number seems missing as of today when accessing the "latest release" version on Github

### ISSUE THREAD

**Issue by generationtech** [OxideMod/Oxide#1262]
Up until today I was able to use this command and pull the current OxideMod version:

`curl -Ls -o /dev/null -w %{url_effective} https://github.com/OxideMod/Oxide/releases/latest | sed -n -e 's/^.*tag\///p'`

I was using it in a variable as part of a larger shell script

`$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/OxideMod/Oxide/releases/latest | sed -n -e 's/^.*tag\///p')`

I've been using this shell script successfully for weeks and weeks, but as of about 4:45pm EST today this stopped working after what seemed like at least 3 different releases of OxideMod builds in short order. Has something changed that now makes my technique of checking current OxideMod version invalid or is there a temporary problem on your end? Thanks

**Comment by lukespragg** [comment]
See http://oxidemod.org/threads/github-repository-changes.28181/.

**Comment by generationtech** [comment]
Ahh. See that now. Adjusted my scripts to new styling. No problem. Thanks
