### ISSUE TITLE
2.0.4300 introduces error: "disconnected: invalid packet: user information"

### ISSUE THREAD

**Issue by quietconundrum** [OxideMod/Oxide#1266]
uMod 2.0.4300 introduces connection error "disconnected: invalid packet: user information" immediately upon clicking the 'connect' button. Rolled back uMod to 2.0.4297 and issue goes away.

**Comment by lukespragg** [comment]
Hello, this repository is not used, but our GitHub is for development only. If you are having a general issue with a build, please use our forums at umod.org. There were no changes in Oxide though, so would be unlikely from our side. The difference between the versions you are using is the patched Rust files from the Rust update.

**Comment by quietconundrum** [comment]
Ok, sorry about that. Just so you're aware, the [uMod git page](https://github.com/theumod/uMod.Rust) links to this specific "Issues tracker" section for support at the [bottom of the page](https://github.com/theumod/uMod.Rust#reporting-security-issues).

**Comment by lukespragg** [comment]
Sorry, that readme is outdated; I'll remove it for now.
