### ISSUE TITLE
Data files cannot be edited outside of the plugin itself

### ISSUE THREAD

**Issue by dcodeIO** [OxideMod/Oxide#157]
I have stumbled upon an issue with how Oxide manages data files. How it is currently, a data file is loaded exactly once and is then cached forever. Only the plugin itself is then able to edit it through code, which makes it impossible to edit the data file, e.g. to correct errors, with the intend to reload the plugin afterwards, expecting it also to reload the data file.

In my exact use case I am trying to fix the data used by the Kits plugin, but I am not able to without restarting the entire server.

Possible solutions could be to remove the cached data structure once a plugin has been unloaded, or to define a timeout of a couple of seconds for caching data files.

Thanks!

**Comment by lukespragg** [comment]
They should be performing the same as config files, so I'm not sure why they wouldn't reload when the plugin is reloaded. @Nogrod

**Comment by dcodeIO** [comment]
Here is the caching:
https://github.com/OxideMod/Oxide/blob/master/Oxide.Core/DataFileSystem.cs#L56

Here it's instantiated exactly once for all plugins:
https://github.com/OxideMod/Oxide/blob/master/Oxide.Core/OxideMod.cs#L143

Doesn't look like data files are bound to a specific plugin / can be removed from the cache.

**Comment by lukespragg** [comment]
Relaying what @bawNg mentioned in IRC:
```
Caching should probably be overridden when a plugin is reloaded. C# plugins should really be using class based data files, which have no caching and are totally managed by the plugin
Data files were never intended to be edited externally, so the caching never accounted for such usage I guess
The C# class based data API needs some work
```

**Comment by lukespragg** [comment]
This should be resolved with the latest commit and upcoming snapshot.

**Comment by dcodeIO** [comment]
That's good news! Thanks and gj as always :)
