### ISSUE TITLE
If a C# plugin fails to compile when first loaded, it cannot be fixed and loaded again

### ISSUE THREAD

**Issue by dcodeIO** [OxideMod/Oxide#158]
Not sure if this has already been fixed, but I have an issue here when installing a new C# plugin that has let's say a syntax error in it, then Oxide will try to compile it and won't let me use "oxide.reload pluginname" again. The error message is like "has already been loaded".

**Comment by lukespragg** [comment]
I can't reproduce this. I believe this was an issue a long time ago, but it should have already been fixed. https://github.com/OxideMod/Oxide/commit/6ca9443c1e0a01ba60538f50f842295fd65e0f12

**Comment by dcodeIO** [comment]
In my exact case I have created a new file Plugin.cs in order to paste the actual contents into it afterwards. When I created the file, being empty, Oxide tried to load the module and failed. After I pasted the contents it couldn't load the plugin again.

**Comment by dcodeIO** [comment]
Thanks! :+1:
