### ISSUE TITLE
Update HooksTest.cs for Oxide.Ext.RustLegacy

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#249]

**Comment by lukespragg** [comment]
Should we update it with internal hooks?

**Comment by lukespragg** [comment]
I added placeholders for the missing ones, excluding the internal ones. Someone should add the parameters and such to them as well either now or when they actually use the parameters to test more.

**Comment by Mughisi** [comment]
Think I got everything for this in PR #313
