### ISSUE TITLE
Add OnItemUse hook

### ISSUE THREAD

**Issue by dcodeIO** [OxideMod/Oxide#31]
I wish there'd be a hook called when any item is used, like when eating meat, using a bandage etc., e.g. to modify the amount healed or the amount of hunger/thirst satisfied.

Currently, this would allow to create plugins that make the different kinds of food actually work, and later on it might be useful for all sorts of general customization.

**Comment by strykes** [comment]
i'll look into it to see if it's possible :)

Reneb
