### ISSUE TITLE
Javascript Prototype Support

### ISSUE THREAD

**Issue by dhershman1** [OxideMod/Oxide#342]
I'm going on a limb, but I was wondering if we could use prototypes in javascript plugins. 

I am assuming we cannot since most of the plugins are just one large object, but I figured I would ask anyway.

something like 
```javascript
stringBuilder: function(player, msg) {
        var x = new stringBuilder();
        x.init({
            player: player,
            msg: "example"
        });
    },

    stringBuilder.prototype.init(options) {
        var player = options.player,
            msg = options.msg,
            color = this.getStringColor(playerid),
            prefix = this.getUserPrefix(player);
    },

    stringBuilder.prototype.getStringColor(id) {
        return data[id].color;
    }
```
I know this isnt a working setup but just a simple example.

**Comment by Calytic** [comment]
Yes it is possible to use prototype in JS plugins.  I am fairly certain that as long as the instantiated global variables matches the name of the plugin then even the plugin itself can be a prototype.  I might be wrong there but generally the answer to your question is yes in any case.

**Comment by dhershman1** [comment]
So, I could do something like 
```javascript
pluginName.prototype.stringBuilder = function(player, msg) {
var x = new stringBuilder();
        x.init({
            player: player,
            msg: "example"
        });
    },
pluginName.prototype.stringBuilder.init = function(options) {
var player = options.player,
            msg = options.msg,
            color = this.getStringColor(playerid),
            prefix = this.getUserPrefix(player);
}
```
While keeping the plugin as an object? Can I declare the prototypes inside the object or should they be built outside the object?
Or ss long as the plugin itself is properly set to 
```javascript
pluginName.prototype = function() {
   Plugin code
};
```

**Comment by Calytic** [comment]
Yea, you're on the right track

```js
var pluginobject = function() {
//...
}

pluginobject.prototype.test = function() {
// ...
}

var globalpluginname = new pluginobject();
```

**Comment by dhershman1** [comment]
So if we decided to keep it all together in the object 
it would probably go like this ?
```javascript
var pluginobject = function() {

  this.testProto: function() {
      //..
    },

    this.testProto.prototype.test: function() {
      //..
    },
    var x = new testProto();
  testProto.test();
}
```
Thanks for the help by the way!

**Comment by lukespragg** [comment]
JavaScript protocol support has been added in PR #344.
