### ISSUE TITLE
CSharp compilation expects specific CSharpCompiler output

### ISSUE THREAD

**Issue by ApocDev** [OxideMod/Oxide#362]
The "PluginCompiler" (more specifically, ObjectStream related classes) expects CSharpCompiler to only put compiler-related "packets" in the output stream. This however, is not always the case, and will cause the entire C# plugin compilation process to get tripped up.

The following is the output from CSharpCompiler.exe when Mono spits out some information.

    Mono: Config attempting to parse: 'G:\rustserv\steamapps\common\lib\..\etc\mono\config'.
    Mono: Assembly Loader loaded assembly from bundle: 'basic.exe'.
    Mono: Assembly Loader probing location: 'G:\rustserv\steamapps\common\lib\mono\4.5\mscorlib.dll'.
    Mono: Assembly Loader loaded assembly from bundle: 'mscorlib.dll'.
    Mono: Image addref mscorlib[002ED778] -> mscorlib.dll[002E2B60]: 2
    Mono: AOT module 'mscorlib.dll.dll' not found: The system cannot find the file specified.
    
    
    
    Mono: AOT module 'G:\rustserv\steamapps\common\lib/mono/aot-cache/x86/mscorlib.dll.dll' not found: The system cannot find the path specified.
    
    
    
    Mono: Config attempting to parse: 'mscorlib.dll.config'.
    Mono: Config attempting to parse: 'G:\rustserv\steamapps\common\lib\..\etc\mono\assemblies\mscorlib\mscorlib.config'.
    Mono: Config attempting to parse: 'C:\Users\ApocDev\.mono\assemblies\mscorlib\mscorlib.config'.
    Mono: Assembly mscorlib[002ED778] added to domain basic.exe, ref_count=1
    Mono: Assembly Loader probing location: 'basic.exe'.
    Mono: Unloading image basic.exe [0036D7D0].
    Mono: Assembly Loader loaded assembly from bundle: 'basic.exe'.
    Mono: Image addref basic[002E9708] -> basic.exe[00319730]: 4
    Mono: Assembly basic[002E9708] added to domain basic.exe, ref_count=1
    Mono: AOT module 'basic.exe.dll' not found: The system cannot find the file specified.
    
    
    
    Mono: AOT module 'G:\rustserv\steamapps\common\lib/mono/aot-cache/x86/basic.exe.dll' not found: The system cannot find the path specified.
    
    
    
    Mono: Config attempting to parse: 'basic.exe.config'.
    Mono: Config attempting to parse: 'G:\rustserv\steamapps\common\lib\..\etc\mono\assemblies\basic\basic.config'.
    Mono: Config attempting to parse: 'C:\Users\ApocDev\.mono\assemblies\basic\basic.config'.
    Mono: Assembly Loader probing location: 'basic.exe'.
    Mono: Unloading image basic.exe [0036D7D0].
    Mono: Assembly Loader loaded assembly from bundle: 'basic.exe'.
    Mono: AOT module 'basic.exe.dll' not found: The system cannot find the file specified.
    
    
    
    Mono: AOT module 'G:\rustserv\steamapps\common\lib/mono/aot-cache/x86/basic.exe.dll' not found: The system cannot find the path specified.
    
    
    
    Mono: Assembly Ref addref basic[002E9708] -> mscorlib[002ED778]: 2
    Mono: Config attempting to parse: 'basic.exe.config'.
    Mono: Assembly Loader probing location: 'G:\rustserv\steamapps\common\lib\mono\gac\System\4.0.0.0__b77a5c561934e089\System.dll'.
    Mono: Assembly Loader loaded assembly from bundle: 'System.dll'.
    Mono: Image addref System[0036DDC8] -> System.dll[002F2F68]: 2
    Mono: Assembly System[0036DDC8] added to domain basic.exe, ref_count=1
    Mono: AOT module 'System.dll.dll' not found: The system cannot find the file specified.
    
    
    
    Mono: AOT module 'G:\rustserv\steamapps\common\lib/mono/aot-cache/x86/System.dll.dll' not found: The system cannot find the path specified.
    
    
    
    Mono: Config attempting to parse: 'System.dll.config'.
    Mono: Config attempting to parse: 'G:\rustserv\steamapps\common\lib\..\etc\mono\assemblies\System\System.config'.
    Mono: Config attempting to parse: 'C:\Users\ApocDev\.mono\assemblies\System\System.config'.
    Mono: Assembly Ref addref basic[002E9708] -> System[0036DDC8]: 2
    Mono: Assembly Ref addref System[0036DDC8] -> mscorlib[002ED778]: 3
    Mono: Assembly Loader probing location: 'G:\rustserv\steamapps\common\lib\mono\gac\System.Core\4.0.0.0__b77a5c561934e089\System.Core.dll'.
    Mono: Assembly Loader loaded assembly from bundle: 'System.Core.dll'.
    Mono: Image addref System.Core[003B2B88] -> System.Core.dll[003DD7C0]: 2
    Mono: Assembly System.Core[003B2B88] added to domain basic.exe, ref_count=1
    Mono: AOT module 'System.Core.dll.dll' not found: The system cannot find the file specified.
    
    
    
    Mono: AOT module 'G:\rustserv\steamapps\common\lib/mono/aot-cache/x86/System.Core.dll.dll' not found: The system cannot find the path specified.
    
    
    
    Mono: Config attempting to parse: 'System.Core.dll.config'.
    Mono: Config attempting to parse: 'G:\rustserv\steamapps\common\lib\..\etc\mono\assemblies\System.Core\System.Core.config'.
    Mono: Config attempting to parse: 'C:\Users\ApocDev\.mono\assemblies\System.Core\System.Core.     ÿÿÿÿ         basic   !ObjectStream.Data.CompilerMessage   <Data>k__BackingField<ExtraData>k__BackingField<Id>k__BackingField<Type>k__BackingField %ObjectStream.Data.CompilerMessageType    
    
          %ObjectStream.Data.CompilerMessageType   value__         ÿÿÿÿ         basic   !ObjectStream.Data.CompilerMessage   <Data>k__BackingField<ExtraData>k__BackingField<Id>k__BackingField<Type>k__BackingField %ObjectStream.Data.CompilerMessageType   
    
          %ObjectStream.Data.CompilerMessageType   value__         ÿÿÿÿ         basic   !ObjectStream.Data.CompilerMessage   <Data>k__BackingField<ExtraData>k__BackingField<Id>k__BackingField<Type>k__BackingField %ObjectStream.Data.CompilerMessageType   
    
          %ObjectStream.Data.CompilerMessageType   value__         ÿÿÿÿ         basic   !ObjectStream.Data.CompilerMessage   <Data>k__BackingField<ExtraData>k__BackingField<Id>k__BackingField<Type>k__BackingField %ObjectStream.Data.CompilerMessageType   
    
          %ObjectStream.Data.CompilerMessageType   value__         ÿÿÿÿ         basic   !ObjectStream.Data.CompilerMessage   <Data>k__BackingField<ExtraData>k__BackingField<Id>k__BackingField<Type>k__BackingField %ObjectStream.Data.CompilerMessageType   
    
    

The easiest fix for this is the following addition in PluginCompiler.CheckCompiler:

    process.Start();
    
    // The CSharpCompiler may spit out some extra lines of standard text if mono search paths
    // aren't being found correctly. This simply checks for that, and lets things read over the stream until
    // we start sending compiler ready messages.
    do
    {
    	string line = process.StandardOutput.ReadLine();
    	if (!string.IsNullOrEmpty(line) && !line.StartsWith("Mono:"))
    		break;
    } while (true);
    
    
    client = new ObjectStreamClient<CompilerMessage>(process.StandardOutput.BaseStream, process.StandardInput.BaseStream);

**Comment by Nogrod** [comment]
Do you have setup any mono environment? Environment variables, installations would be helpful, since a on a clean windows the bundle doesn't behave like this, all output is redirected to our compiler messages. I could reproduce nearly the same issue if i pass special parameters to the mono engine...

**Comment by ApocDev** [comment]
Yes, I have another distro of mono installed (my day-job requires it)

Current mono path vars are set to the "full" install (not Unity's install). This is probably where the issue lies.

**Comment by Nogrod** [comment]
Which mono version do you have installed? And which MONO_* variables are set in your env?

**Comment by lukespragg** [comment]
@ApocDev, try the compiler from https://github.com/Nogrod/Oxide-2/commit/605ace11b4c76892c1e6cae1e42d3281e045020d.

**Comment by lukespragg** [comment]
The latest builds/commits include the fix now, please let us know if you still experience the issue!
