### ISSUE TITLE
CoffeeScript support via Oxide.Ext.JavaScript

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#385]
@bawNg mentioned wanting to add support for this at one point.

**Comment by sean-clayton** [comment]
+1 Would *love* to write in CoffeeScript!

**Comment by dhershman1** [comment]
I'm not a huge fan of Coffeescript to begin with, but would you need to compile coffeescript down to JavaScript like it does now, and then have to compile it again down to C#?

**Comment by lukespragg** [comment]
CoffeeScript would just be an extension of JavaScript.

**Comment by lukespragg** [comment]
Basic support has been added, we'll see where it goes from there. :)
