### ISSUE TITLE
Rust DoRepair hook(s)

### ISSUE THREAD

**Issue by ApocDev** [OxideMod/Oxide#387]
When smacking something with the Hammer, BaseCombatEntity.DoRepair is called. (Or BuildingBlock.DoRepair, as far as other implementations go)

Ideally, both of these would be hooked (one so we can maybe modify repair costs, etc), and the other so we can use the "hammer hit" as a sort of in-game "selection" tool of sorts.

Hammer.DoAttackShared is where this info is used. (Possibly also a hook on Hammer.CanHit for other uses?)

**Comment by lukespragg** [comment]
Added with commit https://github.com/OxideMod/Oxide/commit/3961900d08f1110a52ce9aa849a03d9f9dcc7d32.
