### ISSUE TITLE
C# Plugins - Can't use internal classes

### ISSUE THREAD

**Issue by ApocDev** [OxideMod/Oxide#388]
There's a bug in PluginCompiler.cs in the regex for the "main class" definition.

    match = Regex.Match(line, @"^\s*(?:public |private |protected )?class\s+(\S+)\s+\:\s+\S+Plugin\s*$", RegexOptions.IgnoreCase);

This is checking for "protected" instead of "internal". The "protected" access modifier isn't valid on a top-level class, so I'm not sure if that was intended to be there (or for actually supporting nested classes as plugin "roots")

Either way, internal classes are not supported.

Simple fix:

    match = Regex.Match(line, @"^\s*(?:public |private |protected |internal )?class\s+(\S+)\s+\:\s+\S+Plugin\s*$", RegexOptions.IgnoreCase);

**Comment by lukespragg** [comment]
Resolved with PR #393. Thanks for the report!
