### ISSUE TITLE
Support for C# "out" parameter

### ISSUE THREAD

**Issue by Insnee** [OxideMod/Oxide#389]
Error:
```
[Oxide] 1:03 PM [Error] Failed to call hook 'help' on plugin 'TDCAdmin' (InvalidCastException: Cannot cast from source type to destination type.)
[Oxide] 1:03 PM [Debug]   at Oxide.Plugins.TDCAdmin.help (.BasePlayer player, System.String command, System.String[] args) [0x00000] in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
```

core.cs
```
struct SGiveItem {
            public bool Success { get; set; }
            public string ItemDescription { get; set; }
        }
        private SGiveItem GiveItem(BasePlayer player, string itemname, int amount, ItemContainer container) {
            ...
            return new SGiveItem(){Success=true,ItemDescription=description};
        }
```

admin.cs
```
struct SGiveItem {
            public bool Success { get; set; }
            public string ItemDescription { get; set; }
        }
        [ChatCommand("admin")]
        void help(BasePlayer player, string command, string[] args) {
             ...
             SGiveItem GiveItemResponse;
             GiveItemResponse = (SGiveItem)PTDCCore.Call("GiveItem", (BasePlayer)TargetPlayer, Item, Amount, (ItemContainer)((BasePlayer)TargetPlayer).inventory.containerMain);
```

Isn't the "out" parameter supported?

**Comment by Nogrod** [comment]
should be possible, your error looks like that a cast was not possible somewhere in your help method, without full code not easy to say whats wrong...or perhaps its because you defined the SGiveItem struct in both plugins but its not the same type then, try it without struct, like returning just a ItemDescription on success or use an dictionary...

**Comment by Mughisi** [comment]
You can't use the `out` parameter when using Call or Callhook on a plugin. You can however use the `out` parameter when using the Requires system where you define a required plugin using the magic comment '// Requires: PluginName'. This allows you to call any public method on that plugin including those with parameters like `out` and `ref` with full functionality. If help would be required to have plugins interact with each other using the `Requires` comment please check the forums.
