### ISSUE TITLE
Rename oxide.root.json to oxide.json or oxide.cfg

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#410]
I'm not sure what the purpose of the "root" is in the name aside from the file being in the root directory, but I don't think it's really needed. We'll likely be adding other options in the future, so we may want to consider a more sensible name.

**Comment by thomasfn** [comment]
Originally the intention was to have 2 config files, oxide.root.json AND oxide.json. The idea is for server providers that run multiple instances from the same directory, they can have a single oxide.root.json that governs configuration across ALL their instances, and then an oxide.json per instance for instance specific things. If server providers don't do this and just make a whole new install per server instance, removing root from the name should be fine.

**Comment by lukespragg** [comment]
Ended up renaming it to oxide.config.json, we'll see where it goes from there!
