### ISSUE TITLE
OnServerInitialized only on server load

### ISSUE THREAD

**Issue by neico** [OxideMod/Oxide#420]
I can understand that calling the hook for late loaded plugins makes sense ( #24 & #62 ) but it also causes a specific use case problem, ex. sending a message to slack upon a successful server being ready.

In the current situation any plugin that is loaded after that inital time will always write that message (if you take for example an plugin in development then you'll get spammed with that message which is higly annoying), here's my current hacky workaround:
![](http://puu.sh/iwwbM/115e813536.png)

A way to get around this would be to add a boolean parameter that is only true if it's truely the first time the hook is being called (from ServerMgr like the docs indicate) and after that all calls have that parameter as false, that way there's no need for renaming a hook, making a new one, everything is still combatible and those who need it can simply rely on that parameter

**Comment by Mughisi** [comment]
But what for plugins that load specific stuff that the plugin needs and can only be called in OnServerInitialized?

**Comment by AdamChandler** [comment]
If you really needed to know if it was called from the ServerMgr you could just traverse the callstack looking for the call.

**Comment by neico** [comment]
I just noticed that the above code doesn't even work because OnServerShutdown isn't being forwarded to plugins and Unload doesn't have any indication if it's a command unload / reload or forced by a server shutdown / restart...

I'm beginning to understand why people move to CSharp plugins, if such basic things as determining if it's the server init / shutdown or just the FSWatcher / command doing it's thing isn't even able to be forwarded to a plugin then where's the reason in exposing different languages in the first place?

I mean not even the OxideMod Object is being exposed which would help in working around those things... (Not that I'd like to have hacks around in the first place)

PS: this issue is as easy as changing the following code

```csharp
if (serverInitialized) plugin.CallHook("OnServerInitialized");
```

to

```csharp
plugin.CallHook("OnServerInitialized", serverInitialized);
```

**Comment by lukespragg** [comment]
OnServerShutdown is meant for internal use only. The Unload hook is all plugins really need to use.

**Comment by neico** [comment]
Well something needs to change either way, I don't really care what is being used in the end, but currently there's no way to know if the plugin is being loaded / unloaded on server initialisation / shutdown or by the oxide ConCommands / FSWatcher which is a major issue if you need to do things related to the server behavior as every method that could be used to find that out is being hidden by oxide...

**Comment by lukespragg** [comment]
I see more disadvantages that advantages, and we can't make everyone happy. Your only reason so far as that it's annoying for development, but you could easily add something that disables the the code in OnServerInitialized it for development purposes. There are a lot of server owners that hot-load plugins that utilize this hook, so changing it to how you're suggesting would not be good.

**Comment by neico** [comment]
I'm not sure about the other languages you support but in the case of lua it doesn't care if there's a extra argument being passed along until you actually want to use said argument (I would be actually pretty surprised if it works any different on any language, but there are many strange ones out there so who knows)

Also if you got a problem with adjusting OnServerInitialized then maybe Init() and Unload() would be a good case (as someone already suggested in the case of Unload(): http://oxidemod.org/threads/hook-onserverquit.2601/#post-70597)

The primary issue is that not only the hook itself is missing the indication but that there's none on Unload as well and OnServerShutdown not being called at all, rendering any possible workaround useless.

**Comment by lukespragg** [comment]
Well, I think we'll likely need to add a new hook for this, as renaming the old would cause issues. We're considering OnServerInitializedOnce and OnServerShutdownOnce. Hopefully with our Covalence API we'll be able to start with better names.

**Comment by lukespragg** [comment]
Closing this for now, as there doesn't seem to be any sensible way to resolve the concerns on our end short of adding a new hook which is not ideal. We'll document that the hook is called each time the plugin is loaded. We feel that it should still be called every time it is loaded due to hot-loading after the server has been started.
