### ISSUE TITLE
Access restricted for System.Security.Cryptograph.MD5

### ISSUE THREAD

**Issue by men232** [OxideMod/Oxide#433]
Hi, i have some problems with using **System.Security.Cryptograph**. I'm trying create md5 hash from string (experemental branh) and i have error message:
*System access is restricted, you are not allowed to use System.Security.Cryptograph.MD5*

**Comment by lukespragg** [comment]
Which Oxide build are you using?

**Comment by men232** [comment]
Oxide Version: 2.0.1142

**Comment by lukespragg** [comment]
Which game extension?

**Comment by men232** [comment]
rust

**Comment by lukespragg** [comment]
Make sure you are using System.Security.Cryptography, not System.Security.Cryptograph.

**Comment by men232** [comment]
Yep, i'm using System.Security.Cryptography. Very strange, I see **System.Security.Cryptography** exist in white list, but still have error.

![screen shot 2015-07-09 at 0 35 49](https://cloud.githubusercontent.com/assets/3619283/8582917/77e57d00-25d2-11e5-95de-a2476ab641f6.png)

**Comment by lukespragg** [comment]
Ahh, C#, that's a little different. I've committed a change for that, the upcoming snapshot should allow it. Thanks!

**Comment by men232** [comment]
Thx, its work ;)
