### ISSUE TITLE
Add disconnect reason for player

### ISSUE THREAD

**Issue by neico** [OxideMod/Oxide#435]
In the case of Rust this essentially means moving the OnPlayerDisconnected hook from BasePlayer.OnDisconnected() to ServerMgr.OnDisconnected( connection, strReason ).

This is also what garry suggested to do in order to achieve this as it seems he has no intention of passing the reason string along...

Can't say anything about other games on that matter as I don't own them and just don't care about them either~

**Comment by lukespragg** [comment]
Could you provide an example of what the reason would be needed for?

**Comment by neico** [comment]
If someone timed out,
If somoene was kicked,

**Comment by lukespragg** [comment]
Sorry for the delay! Added this locally, and will be pushing soon!
