### ISSUE TITLE
WebRequest issue on highly populated servers 

### ISSUE THREAD

**Issue by Pho3niX90** [OxideMod/Oxide#450]
Hi.

This error pops up on a highly populated server ( 100+ users), the server has multiple plugins that uses web requests. 

Here is some info.

[7/17/2015 12:55:39 PM] [Oxide] 12:55 PM [Error] Exception raised in web request callback (NullReferenceException: Object reference not set to an instance of an object)
[7/17/2015 12:56:20 PM] [Oxide] 12:56 PM [Error] Exception raised in web request callback (NullReferenceException: Object reference not set to an instance of an object)
[7/17/2015 12:56:20 PM] [Oxide] 12:56 PM [Error] Exception raised in web request callback (NullReferenceException: Object reference not set to an instance of an object)

7:14 PM [Error] Exception raised in web request callback (NullReferenceException: Object reference not set to an instance of an object)
7:14 PM [Debug]  at BasePlayer.SendConsoleCommand (System.String command, System.Object[] obj) [0x00000] in <filename unknown>:0
  at Oxide.Plugins.RustPlugin.PrintToChat (.BasePlayer player, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0
  at Oxide.Plugins.RustPlugin.SendReply (.BasePlayer player, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0
  at Oxide.Plugins.VoteChecker.giveItems (.BasePlayer player, Int32 voteCount) [0x00000] in <filename unknown>:0
  at Oxide.Plugins.VoteChecker.WebRequestCallback (Int32 code, System.String response, .BasePlayer player) [0x00000] in <filename unknown>:0
  at Oxide.Plugins.VoteChecker+<GetRewardsForThisPlayer>c__AnonStorey1.<>m__0 (Int32 code, System.String response) [0x00000] in <filename unknown>:0
  at Oxide.Core.Libraries.WebRequests+WebRequest.<OnComplete>m__1 () [0x00000] in <filename unknown>:0

**Comment by Nogrod** [comment]
Looks like a plugin issue with VoteChecker, in the WebRequestCallback/giveItems should be checked if the player is still connected before using SendReply

**Comment by Pho3niX90** [comment]
I created the plugin and can tell you that I cannot reproduce the error. It only appears on 1 server that is extremely populated. New error:

[Error] Web request produced exception (Url: http://api.cyberscene.co.za/listfor...pi=eotvc3hiauetje0sptgst7scilluq7dgd0i&type=1) (NullReferenceException: Object reference not set to an instance of an object)

(14:55:52) | [Oxide] 4:50 PM [Debug] at Oxide.Core.Libraries.WebRequests+WebRequest.<WaitForResponse>m__0 (IAsyncResult res) [0x00000] in <filename unknown>:0

(14:55:52) | [Oxide] 4:50 PM [Error] Web request produced exception (Url: http://api.cyberscene.co.za/listfor...pi=eotvc3hiauetje0sptgst7scilluq7dgd0i&type=1) (NullReferenceException: Object reference not set to an instance of an object)

(14:55:52) | [Oxide] 4:50 PM [Debug] at Oxide.Core.Libraries.WebRequests+WebRequest.<WaitForResponse>m__0 (IAsyncResult res) [0x00000] in <filename unknown>:0

(14:55:52) | [Oxide] 4:50 PM [Error] Web request produced exception (Url: http://api.cyberscene.co.za/listfor...pi=eotvc3hiauetje0sptgst7scilluq7dgd0i&type=1) (NullReferenceException: Object reference not set to an instance of an object)

(14:55:52) | [Oxide] 4:50 PM [Debug] at Oxide.Core.Libraries.WebRequests+WebRequest.<WaitForResponse>m__0 (IAsyncResult res) [0x00000] in <filename unknown>:0

(14:55:52) | [Oxide] 4:50 PM [Info] Unloaded plugin VoteChecker v1.0.3 by Pho3niX90

**Comment by Pho3niX90** [comment]
Part that calls the url

void GetRewardsForThisPlayer(BasePlayer player)
        {
            if (player.displayName.ToLower() == "server" || player == null) return;


            var playerId = player.userID.ToString();
            webRequests.EnqueueGet("http://api.cyberscene.co.za/listforge/rust.php?steamid=" + playerId + "&ver=" + pluginVersion + "&api=" + Config["listforge_api"] + "&type=" + Config["cyberscene_RewardType"], (code, response) => WebRequestCallback(code, response, player), this);
        }

**Comment by Nogrod** [comment]
It is not the part which starts the webrequests, it is in your WebRequestCallback, the SendReply method uses a rust function:
```csharp
public void SendConsoleCommand(string command, params object[] obj)
{
    ConsoleSystem.SendClientCommand(this.net.connection, command, obj);
}
```
if player.net is null you get this exception

**Comment by Pho3niX90** [comment]
I see, yes this is for a rust server. 

So this is definitely the sendreply? Although that doesn't exist anymore, its now printtochat. 

I thought it might be that the que gets overloaded since he server in question has multiple plugins with the same error that uses webrequest. 

Anyway, I will build in a check and see if that solves the issue

**Comment by bawNg** [comment]
I added the plugin name to the exception message in the latest development snapshot so that it is more clear which plugin is at fault in future. SendReply is a convenience method which can send a reply for chat or console commands.

You need to check that a player is connected before doing anything which requires a connection from a callback which is called asynchronously, such as a web request or timer callback.
