### ISSUE TITLE
Rust 705684 OxideMod 2.0.1192 Object Reference

### ISSUE THREAD

**Issue by l0dac** [OxideMod/Oxide#466]
[7/23/2015 10:45:34 AM] NullReferenceException: Object reference not set to an instance of an object
SaveRestore.ClearMapEntities ()
SaveRestore.Load (System.String strFilename, Boolean allowOutOfDateSaves)
ServerMgr.Initialize (Boolean loadSave, System.String saveFile, Boolean allowOutOfDateSaves, Boolean skipInitialSpawn)
Bootstrap+<StartServer>c__Iterator4.MoveNext ()

**Comment by lukespragg** [comment]
Please provide a full log. From the portion you provided, Oxide doesn't appear to have anything related to that.
