### ISSUE TITLE
Prettify error when attempting to use a chat command via console

### ISSUE THREAD

**Issue by neico** [OxideMod/Oxide#478]
http://puu.sh/jmavG/ad5a2a1016.png

I have a hunch that this error isn't supposed to happen, either parsing it correctly or simply notifing the console about not being able to call this chat command from the console should help there (I'd probably prefer if you could choose via command.AddChatCommand if you want this to trigger on the console as well, I mean /help for example could be a good thing)

But I see this only a minor improvement, nothing serious~
Can be probably coupled with #354

**Comment by lukespragg** [comment]
Chat commands expect a valid user, console commands do not. That is most likely why you are seeing that error. We could add an assumed null check likely, but that's about it.

**Comment by lukespragg** [comment]
This won't really be an issue going forward with the Covalence API, as each command is registered for both chat and console usage.
