### ISSUE TITLE
JS Plugin: unhelpful NullReferenceException

### ISSUE THREAD

**Issue by Rask** [OxideMod/Oxide#486]
I'm developing a plugin using the JavaScript extension.

Now I got an unhelpful exception notice, which doesn't give any pointers as to what the actual error is:

```
Server Network Exception
NullReferenceException: Object reference not set to an instance of an object
```

Nothing else is output to the log. This error happens when I connect to my server on localhost. I got to the section in my plugin which handles player connecting using `OnPlayerInit`, after which nothing happens.

On join, the game screen freezes to

```
LOADING
Receiving data
```

The game is "on", as my CPU usage is pretty high, but my character can't enter the server.

If I could make use of the error messages pasted above, I could do something about the issue.

I'm on the latest 7th August 2015 build of both Rust and Oxide2.

**Comment by Nogrod** [comment]
Example code to reproduce your issue would be nice. Otherwise it is not easy to pinpoint your issue and fix it.

**Comment by Rask** [comment]
I managed to pinpoint the connection issue, and that works now. Still the following method triggers the `NullReferenceException`:

```
    ...

    /**
     * LOGIC
     * Sets the players karma to a certain level. All data saved after an update.
     *
     * @var {Object} player
     * @var {Integer} amount
     */
    setPlayerKarma: function (player, amount)
    {
        print('Setting karma to ' + amount + ' for player ' + player);
        var uid = player.userID.toString();

        // Clamp to min and max values.
        var min = this.Config.minKarma;
        var max = this.Config.maxKarma;

        if (amount > max) {
            amount = max;
        } else if (amount < min ) {
            amount = min;
        }

        // Could not resolve player ID.
        if (!uid) {
            return false;
        }

        // Initialize datafile position for karmas.
        if (!this.dataTable.karmas || this.dataTable.karmas === undefined) {
            this.dataTable.karmas = {};
        }

        this.dataTable.karmas[uid] = parseInt(amount);
        this.SaveDataFiles();

        //interface.CallHook('OnSetPlayerKarma', player);
    },

    ...
```

`SaveDataFiles()` contains the following:

```
    ...
    
    SaveDataFiles: function ()
    {
        print('Saving karma data');
        data.SaveData('karmaSystem');
    }

    ...
```

`SaveDataFiles()` seems to work normally when not triggered from the `setPlayerKarma()` method (I hooked it to the server save Oxide hook too).

**Comment by Nogrod** [comment]
I can't see any issue. And not easy to say what is going wrong without the full plugin. But it looks like the plugin is causing rust to bug and not the js engine. Since hook call errors are catched and wouldn't break game loading

**Comment by lukespragg** [comment]
You may want to check Unity's log, which can be found under RustDedicated_Data/output.txt, or the location as set by -logFile. You should see the full error there, which is likely what Nogrod suggested it is. If you have any further issues, feel free to comment.
