### ISSUE TITLE
Can't use System.Diagnostics

### ISSUE THREAD

**Issue by romgerman** [OxideMod/Oxide#503]
Hello. Just tried to use System.Diagnostics.Stopwatch and...
`UnauthorizedAccessException: System access is restricted, you are not allowed to use System.Diagnostics.Stopwatch`

I want to compare speed of my function and rust function. How can I do that?

P.S. Maybe it's not an issue. Sorry.

**Comment by Nogrod** [comment]
You can use Time.realtimeSinceStartup In Unity games. It will give you the seconds since startup as float value. So just store start & stop that you can calculate the speed for your function.

**Comment by romgerman** [comment]
Oh. Okay. Thanks.
