### ISSUE TITLE
Cleanup/remove old files such as monosgen-2.0.dll and Oxide.Ext.Rust.dll

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#534]
A generic area for processing cleanups might be good.

**Comment by neico** [comment]
For starters a list / file stating which files can be safely removed would help.

For a proper cleanup you'd probably need to ship some sort of bootstrap bat / sh that get's the latest snapshot and automatically detects old files, or simply use a installer.

**Comment by lukespragg** [comment]
The list would be in the code, we've done temporary migrations and cleanup before. A installer or bootstrap wouldn't really be needed.

**Comment by Mughisi** [comment]
This was implemented in https://github.com/OxideMod/Oxide/commit/d9f04fb102e2d7240c4a744ba74aa6f87673a7b4
