### ISSUE TITLE
RustCui newline not working

### ISSUE THREAD

**Issue by eXeGOODER** [OxideMod/Oxide#535]
I think there is no need to tell much.
CuiLabel Text don't support `"\n"`

**Comment by Mughisi** [comment]
The CuiHelper we provide only uses the elements that were made available, we can't add things new things to the clients. 
You'll have to add a separate object for each line of text you want.

**Comment by eXeGOODER** [comment]
@Mughisi , how to make it?

**Comment by LaserHydra** [comment]
We discussed about it and propably got a way to fix that ;)

**Comment by Mughisi** [comment]
@eXeGOODER I have a few ideas that might work but I'll need to look into it but can't right now.

**Comment by eXeGOODER** [comment]
Up

**Comment by lukespragg** [comment]
@Nogrod has a solution for this, and should be committing it shortly.
