### ISSUE TITLE
OnEntityTakeDamage not getting called by player entity

### ISSUE THREAD

**Issue by LaserHydra** [OxideMod/Oxide#540]
[admin] giving LaserHydra 1 x Snap Trap
[admin] giving LaserHydra 1 x Land Mine
[admin] giving LaserHydra 1 x Wooden Floor Spikes
[Oxide] 5:09 PM [Info] [Death Notes] [DEBUG] AT: BroadcastDeath | OnEntityTakeDamage(assets/bundled/prefabs/items/beartrap.prefab[79061], HitInfo)
[Oxide] 5:09 PM [Info] [Death Notes] [DEBUG] AT: BroadcastDeath | -----------------------------------
[Oxide] 5:09 PM [Info] [Death Notes] [DEBUG] AT: HasNeeded? | HasNeeded(LaserHydra[1192/76561198111997160], null)
[Oxide] 5:09 PM [Info] [Death Notes] [DEBUG] AT: HasNeeded? | TryGetLastHit(LaserHydra[1192/76561198111997160])
LaserHydra[1192/76561198111997160] died (Bite)

**Comment by lukespragg** [comment]
Should be resolved already. Duplicate issue #596.
