### ISSUE TITLE
JSON serializer for accessing ProtoStorage permissions

### ISSUE THREAD

**Issue by Calytic** [OxideMod/Oxide#566]
Hi,

Changing the way permissions are stored from JSON to binary (ProtoStorage) has, IMHO, unnecessarily tied oxide permission management to .NET-only applications.  I have multiple web services that relied on the JSON files to manage permissions that are now useless.  I wouldn't mind a change to the data structure, but could we atleast get the option to use a JSON serializer instead of a binary one? 

Thanks,
Calytic

**Comment by lukespragg** [comment]
Completed via PR #586.
