### ISSUE TITLE
Empty errors given sometimes when .cs plugin compilation fails

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#574]
Example:

```
error CS1705: Assembly `Oxide.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' depends on `Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version number than referenced assembly `Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
```

![fb19942859c2661164d44ec6489f159b](https://cloud.githubusercontent.com/assets/671337/10556939/8b065014-7463-11e5-92a2-e840f9f11252.png)
##

**Comment by lukespragg** [comment]
Still an issue, happened today. It may not happen a lot, mainly when a dependency is wrong, but I'm sure there are other instances.

**Comment by int128fly** [comment]
just happen to me, my plugin failed to compile and got an other error line under empty. How you fix it?

**Comment by lukespragg** [comment]
You can generally see the actual error in your compiler log @int128fly, but there is no fix right now which is why the issue is still open.
