### ISSUE TITLE
variable passing to Lua Plugins issue

### ISSUE THREAD

**Issue by LaserHydra** [OxideMod/Oxide#588]
When trying to get C# type variables like "long" from a Datafile which was created by a C# plugin, the lua plugin already recieves the value as a lua number type. Lua does not like these values, so the values are not correct. Would propably be fixable using :ToString(), but as Oxide already passed it to the plugin as a "number" type variable, its to late for that.

**Comment by lukespragg** [comment]
From @Mughisi:

> The variable passing for Lua is something plugin authors just need to keep in mind. Lua just doesn't support the long ints.
