### ISSUE TITLE
Hurtworld: Extensions not working

### ISSUE THREAD

**Issue by Bombardir** [OxideMod/Oxide#605]
Custom extensions not working until you save server...
To make custom extensions work you need:
1) Start server
2) Save server
3) Restart server

**Comment by lukespragg** [comment]
There are extensions bundled with Oxide, so they are indeed working fine.

**Comment by Bombardir** [comment]
Oh, extension working but hooks not (until save-restart). I can't give an example, but i'm using this extension in Rust too and it's working fine.

**Comment by lukespragg** [comment]
I can't give you any explanation for that, but there are no differences other than default hooks available.

**Comment by Bombardir** [comment]
This problem occurs only on new or wiped servers, so you can try to reproduce it.

**Comment by lukespragg** [comment]
Without a more detailed example, I can't re-produce that. I've wiped and used Oxide's default extensions hundreds of times without issues over the past few months with Hurtworld.

**Comment by Bombardir** [comment]
Save or restart don't affect on hooks working, it's happen when server loads without Map.
My extension loads custom plugins from web server and they will not work on server until he will start with saved map.

**Comment by lukespragg** [comment]
It sounds like an issue with when your plugins are trying to do things. The Hurtworld server takes longer to initialize when generating a new map than with an existing map, so you may need to consider that

**Comment by Bombardir** [comment]
Oh, i thinks i know what problem is. My plugins will work only with "OnServerInitialized" hook, but this hook called from function 'LoadServer(string filename)' that causes error when server can't find map.

**Comment by lukespragg** [comment]
We may be able to move the hook to a later point, I'll let you know.

**Comment by Bombardir** [comment]
Thanks

**Comment by lukespragg** [comment]
The next snapshot will have a better OnServerInitialized location. :)
