### ISSUE TITLE
HurtWorld plugins stop work with update 2.0.1637

### ISSUE THREAD

**Issue by sharpblades** [OxideMod/Oxide#608]
HurtWorld plugins stop work with update 2.0.1637 with no errors... just not work

**Comment by lukespragg** [comment]
Use /version in-game to check if you have Oxide installed. Nothing changed with how plugins are loaded, so the only reason plugins wouldn't load is if Oxide wasn't installed.

Also, please use the forums for general support. The GitHub issues are for keeping tracking of bugs, tasks, etc.
