### ISSUE TITLE
HurtWorld, linux, "Only access to oxide directory" error

### ISSUE THREAD

**Issue by helgaborjomi** [OxideMod/Oxide#612]
Oxide.Core/Configuration/DynamicConfigFile.cs : 124
Change:
return name.TrimStart('.', Path.DirectorySeparatorChar);
To:
if (Environment.OSVersion.Platform == PlatformID.Unix)
{
return name;
}
return name.TrimStart('.', Path.DirectorySeparatorChar);

**Comment by lukespragg** [comment]
I'm not sure that's the best fix for it, but we'll have a fix available soon for this and some other issues with Linux builds. Thanks!
