### ISSUE TITLE
HurtWorld: OnPlayerSpawn not works

### ISSUE THREAD

**Issue by sharpblades** [OxideMod/Oxide#624]
OnPlayerSpawn not works on Version 2.0.1720

**Comment by lukespragg** [comment]
The hook hasn't changed and is still in the same position. What are you trying to do with it?

**Comment by sharpblades** [comment]
private void OnPlayerSpawn(PlayerSession player)
        {
               Puts("TEST");
        }

**Comment by lukespragg** [comment]
Are you sure your plugin is loaded? It's working fine for me.

![d69655373f4ee72012cf5fab67b1d558](https://cloud.githubusercontent.com/assets/671337/12343518/7199a320-bb02-11e5-902e-770ea1f43d75.png)

**Comment by sharpblades** [comment]
WOW LOL... big sorry ... my bad ... i need use OnPlayerRespawn

**Comment by lukespragg** [comment]
OnPlayerRespawn also working:

![459d592e114ce199e3c0eb6915170f11](https://cloud.githubusercontent.com/assets/671337/12343561/bf61e9b4-bb02-11e5-8418-0d2360c54a84.png)

**Comment by sharpblades** [comment]
big sorry, all works!

**Comment by lukespragg** [comment]
No problem. :)
