### ISSUE TITLE
Remove the need of registering permission nodes

### ISSUE THREAD

**Issue by recon88** [OxideMod/Oxide#631]
I'm wondering why it is necessary to register permissions. Without that we would be able to create things like this:

```
int limit = 0;
            foreach (String permission in permission.GetUserPermissions(uid.ToString())) {
                if (permission.StartsWith("shop.buylimit."))
                {
                    limit = Int32.Parse(permission.Split(new[] { "shop.buylimit." }, StringSplitOptions.None)[1]);
                }
            }
```

Things like that are possible in some other APIs I worked with. They only store the permissions and groups a user has. Plugins can ask for every permission node they want and don't have to register them.

-> Player joins: Load saved permissions and groups
-> Plugin asks for permission node "hello.canworld": Server checks the user's perm list and returns bool

Hope something like this will be possible in the future :)

**Comment by lukespragg** [comment]
I think the permissions were designed with registration for a specific
reason. One of those reasons likely being that you can't check if a
permissions is valid without registration, and you can't assure permissions
are unique per plugin unless you either have registration or require/force
a namespace with permissions from plugins.

You can however dynamically register multiple permissions if you wanted to,
and wildcards are supported for checking as well, so I'm not sure what it
is you're asking that can't already be done.

**Comment by recon88** [comment]
Didn't know wildcards were possible. Thanks for the information.
Will give it a try.

**Comment by lukespragg** [comment]
Not sure if you worked this out already or not, but you could dynamically register permissions as needed too, similar to how plugins such as Kits, Better Chat, and others do. You don't have to have one static permission per line you can loop through whatever you'd like and add them as needed when needed.
