### ISSUE TITLE
ECMAScript 6 Support

### ISSUE THREAD

**Issue by dhershman1** [OxideMod/Oxide#641]
Is it possible to implement the use of ES6 style syntax?
It offers a lot of benefits and methods that will open up faster more fluid code development.

Including
- Default Parameters
- Multi line strings
- Arrow Functions
- Freaking Object Destructing and Array Matching
- Block scoped Constructs let and const
- Typed Arrays
- Classes
- Template Literals
- Modules (However I really doubt that this is a note worthy feature for oxide plugin development lol unless used with namespace?)

List of the current finalized ES6 Features: http://es6-features.org/

I just thought it would be a great implementation to consider with the benefits to both performance and flow ES6 brings.

**Comment by neico** [comment]
The problem is that JInt which the js extension is based on is a 5.1 one. unless you're able to provide a interpreter that builds onto es6 this won't be possible...

**Comment by dhershman1** [comment]
Ah, shame we can't use modules or I'd throw babel into the mix for ideas. Oh well, maybe if I can learn more C# I would look into building an interpreter.
