### ISSUE TITLE
Plugin version as x.x.x.x string not returning 4th part

### ISSUE THREAD

**Issue by LaserHydra** [OxideMod/Oxide#647]
Oxide only saves maximal three parts of a version. 
1.2.3.4 is not saved. 
-> Shows as 1.2.3

**Comment by lukespragg** [comment]
Pretty sure it "saves" it fine, it just doesn't grab the third part when converting to string. ;)

**Comment by lukespragg** [comment]
So the reasoning behind this... is that Oxide uses the Semantic Versioning. I could add support for a 4th version part, but it would break all of the extensions (official and third-party) and require all to be updated.
