### ISSUE TITLE
CSharpCompiler not working on Linux

### ISSUE THREAD

**Issue by XL-Reaper** [OxideMod/Oxide#651]
CSharpCompiler doesn't seem to work for Oxide Rust linux server on Ubuntu 12.04

./CSharpCompiler: error while loading shared libraries: libmonoboehm-2.0.so.1: cannot open shared object file: No such file or directory

Steps to reproduce:
wget https://raw.githubusercontent.com/OxideMod/Snapshots/master/Oxide-Rust_Linux.zip

Unzip, run ./CSharpCompiler

**If i install the missing library that changes to:**
Corlib not in sync with this runtime: expected corlib version 111, found 138.
Loaded from: mscorlib.dll

**Comment by lukespragg** [comment]
CSharpCompiler is not meant to be manually ran. Just install it and let Oxide run it when it needs to.

**Comment by XL-Reaper** [comment]
The problem is: the plugins don't compile.
21:20 [Error] InfoPanel plugin failed to compile!
21:20 [Error] Compiler disconnected.

**Comment by lukespragg** [comment]
No, that would be a missing system dependency most likely. See http://oxidemod.org/threads/rust-server-on-linux-natively.16255/#post-182752.

**Comment by XL-Reaper** [comment]
Like I wrote in the forum:
I've found the solution: Oxide doesn't seem to respect the custom LD_LIBRARY_PATH I've set.
After I copied the libraries to rust_dedicated/RustDedicated_Data/Managed/x86 and rust_dedicated/RustDedicated_Data/Managed/x64 the plugins do compile now.

**Comment by lukespragg** [comment]
The libraries should already exist in those paths, if not then the install isn't complete.

**Comment by XL-Reaper** [comment]
I do mean the System libraries like libc6, not the libmono-thing I mentioned at the start. In my current setup I dont have them in the normal System library path, but in an extra steam folder. Works fine for rust, but the plugins don't compile this way.
Anyways it's solved, thanks for pointing me in the right direction.

----- Ursprüngliche Nachricht -----
Von: "Luke Spragg" <notifications@github.com>
Gesendet: ‎09.‎03.‎2016 21:43
An: "OxideMod/Oxide" <Oxide@noreply.github.com>
Cc: "XL-Reaper" <t.seip@werner-seip.de>
Betreff: Re: [Oxide] CSharpCompiler not working on Linux (#651)

The libraries should already exist in those paths, if not then the install isn't complete.
