### ISSUE TITLE
[python] webrequest is not defined

### ISSUE THREAD

**Issue by zloidemon** [OxideMod/Oxide#656]
When I called webrequest is not defined, I also tried to import modules - it didn't work. I can System.Net and it works but more better use webrequest helpers than write same code in python on System.Net.

```
RuntimeError: Failed to call Init (UnboundNameException: global name 'webrequest' is not defined)
```

**Comment by Nogrod** [comment]
the name should be 'webrequests'

**Comment by zloidemon** [comment]
It works. Thank you!
