### ISSUE TITLE
Alternative for main configuration instead of JSON

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#67]
As suggested by @bawNg.

```
ExtensionDirectory: RustDedicated_Data\Managed

PluginDirectory: plugins
ConfigDirectory: config
DataDirectory: data
LogDirectory: logs
TempDirectory: temp

InstanceCommandLines:
 - "{oxide.directory}"
  - "server\{server.identity}\oxide"
  - "server"
```

**Comment by thomasfn** [comment]
I hate YAML with a passion. I still have nightmares about line endings.

**Comment by lukespragg** [comment]
Line endings and tabs are my concerns as well. I've seen too many issues from people messing up their configs with those. It is more user friendly in terms of layout though, but I'd like to be able to try to handle user errors if it were to be implemented.

**Comment by thomasfn** [comment]
If it's a regularly requested feature, it could be optional. For example, when querying for the config file "myconfig", Oxide will search for both "myconfig.json" and "myconfig.yaml/yml" and select the one with the most recent edit date (or throw an error if both are present). That way users can pick or select an option. 

It's probably better to stick with one though for consistency, and overhauling the entire config system + forcing all server owners to reconfigure their servers just to have yaml over json doesn't sound like a great idea to me.

**Comment by lukespragg** [comment]
@bawNg talked about automatically converting JSON configs to YAML, as we wouldn't want to cause issues.

**Comment by bawNg** [comment]
I haven't heard of issues with line endings, I also haven't ever experienced issues using YAML implementations on Windows or Linux. The chosen .Net YAML implementation could be tested and if necessary, adding a simple pre-parser to fix edge case issues would be trivial. I've done that in the past for correcting quotations around paths.

**Comment by aequasi** [comment]
Never heard of line ending issues either. And indentation errors give you a pretty simple and understandable error on the location of the offense.

**Comment by lukespragg** [comment]
Closing for now as I don't see this happening anytime soon, if at all. JSON is the primary configuration method plugins use, so users are pretty familiar with it at this point.
