### ISSUE TITLE
GUI examples for JavaScript

### ISSUE THREAD

**Issue by fenixrus** [OxideMod/Oxide#670]
Hello, I could not find the working pieces of code or actual documentation.
Sorry, My sentence structure is very bad.
Help my please.

**Comment by fenixrus** [comment]
I could find example (http://oxidemod.org/threads/javascript-cuihelper-plugin-lib-wip.12943). But he is not working(

**Comment by lukespragg** [comment]
This should be posted at https://github.com/OxideMod/Docs/issues, but we are working on updating the docs.
