### ISSUE TITLE
I'm used branch master Windows 7 and have error and not work mode.

### ISSUE THREAD

**Issue by gragonvlad** [OxideMod/Oxide#675]
> version
Oxide version: 2.0.0, Rust Protocol: 1069
rust.
Server DataDir
C:\Program Files (x86)\GreatGames.su\steamcmd\steamapps\common\rust_dedicated\
serverdata\
Loaded serverdata/cfg/server.cfg
The referenced script on this Behaviour is missing!
Instantiator for prefab 'barrel_A1_01' already exists
[Oxide] 16:00 [Info] Loading Oxide Core v2.0.0...
[Oxide] 16:00 [Info] Loading extensions...
[Oxide] 16:00 [Info] Loaded extension CSharp v1.0.0 by Oxide Team
[Oxide] 16:00 [Info] Loaded extension JavaScript v1.0.0 by Oxide Team
[Oxide] 16:00 [Error] Failed to load extension Oxide.Ext.Lua (DllNotFoundExcepti
on: lua52)
[Oxide] 16:00 [Debug]   at (wrapper managed-to-native) KeraLua.NativeMethods:Lua
LNewState ()
at KeraLua.Lua.LuaLNewState () [0x00000] in <filename unknown>:0
at NLua.LuaLib.LuaLNewState () [0x00000] in <filename unknown>:0
at NLua.Lua..ctor () [0x00000] in <filename unknown>:0
at Oxide.Ext.Lua.LuaExtension.InitializeLua () [0x00000] in <filename unknown>
:0
at Oxide.Ext.Lua.LuaExtension.Load () [0x00000] in <filename unknown>:0
at Oxide.Core.Extensions.ExtensionManager.LoadExtension (System.String filenam
e) [0x00000] in <filename unknown>:0
[Oxide] 16:00 [Info] Loaded extension MySql v1.0.0 by Oxide Team
[Oxide] 16:00 [Info] Loaded extension Python v1.0.0 by Oxide Team
[Oxide] 16:00 [Info] Loaded extension SQLite v1.0.0 by Oxide Team
[Oxide] 16:00 [Info] Loaded extension Unity v1.0.0 by Oxide Team
[Oxide] 16:00 [Error] Failed to load extension Oxide.Game.Rust (ReflectionTypeLo
adException: The classes in the module cannot be loaded.)
[Oxide] 16:00 [Debug]   at (wrapper managed-to-native) System.Reflection.Assembl
y:GetTypes (bool)
at System.Reflection.Assembly.GetExportedTypes () [0x00000] in <filename unkno
wn>:0
at Oxide.Core.Extensions.ExtensionManager.LoadExtension (System.String filenam
e) [0x00000] in <filename unknown>:0
[Oxide] 16:00 [Info] Loaded extension RustLegacy v1.0.0 by Oxide Team
[Oxide] 16:00 [Info] Using Covalence provider for game 'Rust Legacy'
[O

My OC Windows 7 Ultimate x64 , Programm Microsoft Visual c++ 2012 (x640 , mvc++ 2008 x86  Microsoft Visual c++ 2010 x64 , .mvc ++2012 mvc++2013 mvc++2015 redist Microsoft Visual Studio Community 2015 with Update 1  , OpenSSL 1.0.1 p  . I'm install oxidemod last version for rust legacy  last version with steamcmd last . And have this errors. Nide help .  Thats version stabile ?  This mode have commands /home /about /ping ?

**Comment by lukespragg** [comment]
Please use our forums at http://oxidemod.org for general support.

No chat commands are included by default with Oxide, they are provided by plugins. You also seem to be missing some files included with Oxide, and also seem to be using Oxide.Ext.Rust when you should only be using Oxide.Ext.RustLegacy.
