### ISSUE TITLE
Hurtworld OnPlayerChat hook breaks if a message is null

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#682]
This may only be an issue with Covalence, I just need to check it out.
##

**Comment by Mughisi** [comment]
Is this still an issue? Tried both OnUserChat and OnPlayerChat in a covalence plugin and OnPlayerChat in a HW plugin and I was unable to reproduce any errors with the hook.

**Comment by lukespragg** [comment]
I'm not sure, I tested yesterday and couldn't reproduce it, so I'm not sure what was causing it before.

**Comment by lukespragg** [comment]
Closing as I can no longer reproduce this.
