### ISSUE TITLE
Rust API Misspellings

### ISSUE THREAD

**Issue by ScottButler87** [OxideMod/Oxide#687]
The following API function definitions incorrectly spell privilege as both privlidge and priviledge. Additionally, OnCupboardDeauthorize incorrectly Puts("OnCupboardAuthorize...").

```C#
void OnCupboardAuthorize(BuildingPrivlidge priviledge, BasePlayer player)
{
    Puts("OnCupboardAuthorize works!");
}

void OnCupboardClearList(BuildingPrivlidge priviledge, BasePlayer player)
{
    Puts("OnCupboardClearList works!");
}

void OnCupboardDeauthorize(BuildingPrivlidge priviledge, BasePlayer player)
{
    Puts("OnCupboardAuthorize works!");
}
```

**Comment by lukespragg** [comment]
The first is actually right, it has to be spelled that way for Rust as it
is misspelled in Rust. The second can be fixed though.

**Comment by lukespragg** [comment]
Fixed what can be fixed, thanks. ;)

**Comment by ScottButler87** [comment]
Thank you.
