### ISSUE TITLE
[Hurtworld] savepath Not available

### ISSUE THREAD

**Issue by cokll** [OxideMod/Oxide#721]
<pre>
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

System.String[]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

System.String[]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

Invalid format, you must enter savepath <absolutePath>
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 13:13 [Info] Loading Oxide Core v2.0.2086...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 13:13 [Info] Loading extensions...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 13:13 [Info] Loaded extension CSharp v1.0.2086 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 13:13 [Info] Loaded extension JavaScript v1.0.2086 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 13:13 [Info] Loaded extension Lua v1.0.2086 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 13:13 [Info] Loaded extension MySql v1.0.2086 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 13:13 [Info] Loaded extension Python v1.0.2086 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 13:13 [Info] Loaded extension SQLite v1.0.2086 by Oxide Team</pre>

**Comment by lukespragg** [comment]
Oxide doesn't control any of the game's start information, you may want to contact the game's authors.

**Comment by cokll** [comment]
I confirmed that it was a problem caused by MaxPlayers[patch]

**Comment by lukespragg** [comment]
I don't see how, that patch has been in same place for quite a long time. All it does is change the number 60 to 244.

**Comment by cokll** [comment]
I used Oxide Patcher canceled, savepath normal.

**Comment by lukespragg** [comment]
If you made a custom build, that is not supported. We cannot support what you may or may not have changed. In the official builds there are no issues with that patch or the save path.

**Comment by cokll** [comment]
I oxidemod.org download Oxide-Hurtworld.zip,savepath invalid.
I used Oxide Patcher test patch,Found MaxPlayers [patch] problem

**Comment by lukespragg** [comment]
I can't reproduce that, no other reports either. Make sure that you aren't using a custom build please.

**Comment by cokll** [comment]
my start cmd:Hurtworld.exe -batchmode -nographics -exec "host 12871;queryport 12881;servername test;maxplayers 10000;playerlootmode 0;savepath E:\server\hurtworld" -logfile "gamelog.txt"

Oxide-Hurtworld.zip
MD5: 84F245498D7BB1B2FF759D5AB9579FB5
SHA1: CF01841AE2BBD1CF76E2EC9B0E0518AD289A4E3F
CRC32: 8D9CCF04

<pre>Initialize engine version: 5.3.4f1 (fdbb5133b820)
Forcing GfxDevice: Null
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\I18N.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Assembly-UnityScript.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\Assembly-UnityScript.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\AmplifyMotion.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\AmplifyMotion.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Pathfinding.ClipperLib.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\Pathfinding.ClipperLib.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Pathfinding.Ionic.Zip.Reduced.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\Pathfinding.Ionic.Zip.Reduced.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Pathfinding.JsonFx.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\Pathfinding.JsonFx.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Pathfinding.Poly2Tri.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\Pathfinding.Poly2Tri.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\NSpeex.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\NSpeex.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Rewired_Core.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\Rewired_Core.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\uLink.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\uLink.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\ArabicSupport.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\ArabicSupport.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\EasyAntiCheat.Client.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\EasyAntiCheat.Client.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\EasyAntiCheat.Server.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\EasyAntiCheat.Server.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.Cloud.Analytics.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.Cloud.Analytics.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.Cloud.Analytics.Util.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.Cloud.Analytics.Util.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\I18N.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\I18N.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\I18N.West.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\I18N.West.dll into Unity Child Domain
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.CrashLog.dll (this message is harmless)
Loading E:\server\hurtworld\Hurtworld_Data\Managed\UnityEngine.CrashLog.dll into Unity Child Domain
- Completed reload, in  0.073 seconds
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Boo.Lang.dll (this message is harmless)
WARNING: Shader Unsupported: 'Particles/Refraction' - All passes removed
WARNING: Shader Unsupported: 'Particles/Refraction' - Setting to default shader.
Shader 'Debug/Advanced': dependency 'BaseMapShader' shader 'Debug/Advanced' not found
The referenced script on this Behaviour (Game Object 'PlayerServerLoadTest') is missing!
 
(Filename:  Line: 1655)

UnloadTime: 1.569164 ms
Starting Game. Save Version: 0.3.6.0	Protocol Version: 36	Send Buffer Size: 131071
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Mono.Security.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.Configuration.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.Xml.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Oxide.Core.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Newtonsoft.Json.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.Runtime.Serialization.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.Xml.Linq.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.Data.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\protobuf-net.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Oxide.Ext.CSharp.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Mono.Cecil.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Oxide.Ext.JavaScript.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Jint.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Oxide.Ext.Lua.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\NLua.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\KeraLua.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Oxide.Ext.MySql.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\MySql.Data.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Oxide.Ext.Python.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Microsoft.Scripting.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\IronPython.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Microsoft.Dynamic.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Microsoft.Scripting.Core.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\IronPython.Modules.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Oxide.Ext.SQLite.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.Data.SQLite.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Oxide.Ext.Unity.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Oxide.Game.Hurtworld.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.Transactions.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\System.Configuration.Install.dll (this message is harmless)
Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Mono.Data.Tds.dll (this message is harmless)
System.String[]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

System.String[]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

System.String[]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

System.String[]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

System.String[]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

System.String[]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

Invalid format, you must enter savepath <absolutePath>
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loading Oxide Core v2.0.2089...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loading extensions...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded extension CSharp v1.0.2089 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded extension JavaScript v1.0.2089 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded extension Lua v1.0.2089 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded extension MySql v1.0.2089 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded extension Python v1.0.2089 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded extension SQLite v1.0.2089 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded extension Unity v1.0.2089 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded extension Hurtworld v1.0.2089 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Using Covalence provider for game 'Hurtworld'
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loading plugins...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded plugin Unity Core v1.0.0 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 18:57 [Info] Loaded plugin Hurtworld v1.0.0 by Oxide Team
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

Steam GameServer initialized
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

</pre>

**Comment by lukespragg** [comment]
You can't have 10000 maxplayers, the highest is 244. The error is with your -savepath usage.

**Comment by cokll** [comment]
I modified to 244 still the same error

**Comment by lukespragg** [comment]
Because the error is from the maxplayers, I was just mentioning that you can't have 10000.

Try setting your path to a folder under your server's root, not a full path.

**Comment by cokll** [comment]
my test cmd :Hurtworld.exe -batchmode -nographics -exec "host 12871;queryport 12881;savepath E:\server" -logfile "gamelog.txt"
Still the same error.

**Comment by lukespragg** [comment]
Set it to a folder in your server's root, not a path.

**Comment by cokll** [comment]
I used Oxide Patcher unset MaxPlayers [patch] ,no problem
<pre>Platform assembly: E:\server\hurtworld\Hurtworld_Data\Managed\Mono.Data.Tds.dll (this message is harmless)
> host 12871

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

> queryport 12881

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

> savepath E:\server

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

Set savepath to E:\server
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 19:07 [Info] Loading Oxide Core v2.0.2089...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

[Oxide] 19:07 [Info] Loading extensions...
 </pre>

**Comment by lukespragg** [comment]
Okay, so the issue wasn't with the maxplayers patch, it was with another. I doubt many change the savepath, so it wasn't coming up. I have already fixed the patch that was causing it, I'll push out a fix for it shortly. Thanks for the report!
