### ISSUE TITLE
[Hurtworld] Win2008 R2 plugin failed to compile!

### ISSUE THREAD

**Issue by cokll** [OxideMod/Oxide#728]
<pre>14:44 [Info] Loading Oxide Core v2.0.0...
14:44 [Info] Loading extensions...
14:44 [Info] Loaded extension CSharp v1.0.0 by Oxide Team
14:44 [Info] Loaded extension JavaScript v1.0.0 by Oxide Team
14:44 [Info] Loaded extension Lua v1.0.0 by Oxide Team
14:44 [Info] Loaded extension MySql v1.0.0 by Oxide Team
14:44 [Info] Loaded extension Python v1.0.0 by Oxide Team
14:44 [Info] Loaded extension SQLite v1.0.0 by Oxide Team
14:44 [Info] Loaded extension Unity v1.0.0 by Oxide Team
14:44 [Info] Loaded extension Hurtworld v1.0.0 by Oxide Team
14:44 [Info] Using Covalence provider for game 'Hurtworld'
14:44 [Info] Loading plugins...
14:44 [Info] Loaded plugin Unity Core v1.0.0 by Oxide Team
14:44 [Info] Loaded plugin Hurtworld v1.0.0 by Oxide Team
14:45 [Error] BetterChat plugin failed to compile!
14:45 [Error] Compiler disconnected.
14:47 [Error] BetterChat plugin failed to compile!
14:47 [Error] Compiler disconnected.
14:47 [Error] CustomDeathMessages plugin failed to compile!
14:47 [Error] Compiler disconnected.
</pre>
Img:http://i.imgur.com/TtUXmr6.jpg
img:http://i.imgur.com/Kmm3N5G.jpg
I tested the windows server 2012 does not have this problem

**Comment by lukespragg** [comment]
Please use the forums for general support. "Compiler disconnected" is the compiler being outdated or not fully updated.
