### ISSUE TITLE
error CS1061

### ISSUE THREAD

**Issue by neon-cat** [OxideMod/Oxide#729]
[Oxide] 01:20 [Error] Error while compiling FastSmelt.cs(54,18): error CS1061: Type `Inventory' does not contain a definition for `ItemTickDelay' and no extension method `ItemTickDelay' of type `Inventory' could be found. Are you missing an assembly reference?

**Comment by lukespragg** [comment]
Please report the issue on the plugin's support thread. The issue tracker here is not for general support.
