### ISSUE TITLE
Add System.Net to the whitelist

### ISSUE THREAD

**Issue by leo318x** [OxideMod/Oxide#73]
Add System.Net to the whitelist to use some web protocols, thanks ;)

**Comment by lukespragg** [comment]
You'd need to use the webrequests API in Oxide. The whitelist/blacklist is there to prevent abuse.

**Comment by leo318x** [comment]
I did not know there was an API on that, sorry to do this x).

**Comment by lukespragg** [comment]
Yup! You can see an example of it in plugins such as Rust Metrics, Country Block, Natives, Analytics, Notifico, and more.

**Comment by leo318x** [comment]
Thanks buddy, I'm on it! :)
