### ISSUE TITLE
OnServerCommand hook blocking ability

### ISSUE THREAD

**Issue by serg1980serg** [OxideMod/Oxide#771]
http://prnt.sc/c4sa74
Этот хук нужен для блокирования команд во время ивентов.
Можете ли вы этот хук внедрить в Оксиде?
This hook is needed to lock the input commands during the events.
Can you implement this hook in the oxide?
http://prnt.sc/c4se25

**Comment by Mughisi** [comment]
The hook OnServerCommand(ConsoleSystem.Arg arg) is hooked in ConsoleSystem.Run.Internal and should already allow you to block commands.

**Comment by serg1980serg** [comment]
http://prntscr.com/c4t0ke
It does not block.
What am I doing wrong?

**Comment by serg1980serg** [comment]
thanks for the quick work
