### ISSUE TITLE
Need later hook location for OnServerInitialized

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#789]
Right now Steam isn't initialized where the hook currently is in Rust, and I believe 7 Days to Die as well. The later point is needed to get server.Address.
##

**Comment by lukespragg** [comment]
Also need this for Unturned, somewhere that has LightingManager.time set.

**Comment by Mughisi** [comment]
Not sure that we should actually do this, maybe we can add a OnSteamInitialized hook somewhere instead as the initialization of the server.Address and such is made available through various callbacks.

**Comment by lukespragg** [comment]
Why @Mughisi? I don't see any harm in bumping it slightly later. The server isn't fully initialized if the address isn't available.

**Comment by lukespragg** [comment]
This isn't an issue anymore as we no longer use Steam to handle it. For the games still using Steam, they'll be switched to the new method.
