### ISSUE TITLE
OnTrapTrigger isn't working

### ISSUE THREAD

**Issue by Sugydro** [OxideMod/Oxide#824]
**OnTrapTrigger** isn't work.

I'm use **OnTrapSnapped** and **OnEnitityEnter** instead, so I think this hook can be removed.
##

**Comment by lukespragg** [comment]
It only works for certain trap types, and should still work based on that trap type only.

**Comment by Sugydro** [comment]
Which type? I'm tested with Landmine and BearTrap.

**Comment by lukespragg** [comment]
It says BaseTrap, so not sure if that covers Landmine and BearTrap or not.

**Comment by Sugydro** [comment]
Now I'm tested with all existing traps, no reaction.
