### ISSUE TITLE
Why support latest version of .NET Framework dropped to old versions?

### ISSUE THREAD

**Issue by eXeGOODER** [OxideMod/Oxide#839]
Plugins stopped working with .NET Framework higher 3.5;

* error CS0117: 'string' does not contain a definition for 'IsNullOrWhiteSpace'
* json datafiles was broken

**Comment by lukespragg** [comment]
Oxide uses .NET 3.5 for all Unity-based games, so anything available in 3.5 you can use in plugins. Nothing has changed with this in 3 years.
