### ISSUE TITLE
Testing plugins without running a server

### ISSUE THREAD

**Issue by romgerman** [OxideMod/Oxide#846]
Hi. I thought that it would be great if plugin developers could test their plugins without running a game server.
I tried to run oxide with only console window but for some reason several extensions are not loading and gives me "IO Exception". I don't quite understand how oxide works inside and that's why i'm writing this. I also thought that it would be cool to debug plugins in VS (with breakpoints and stuff).

If it's not possible (why it shouldn't be possible?) then well... i'll continue to run Rust server that eats 1.5GB of RAM and 10+% CPU and game that eats a lot more. But anyway you are doing a great job. Thank you.

**Comment by lukespragg** [comment]
You can debug plugins in Visual Studio in terms of code errors, but there is nothing to simulate hook calling outside of running a server. I'd recommend running a local server for testing. If you are having errors, then we'd need to see the logs, but that's something I'd recommend posting on the forums.

**Comment by romgerman** [comment]
Why not? You can simulate hooks by just calling them. I tried to load Oxide for simple console application:

```csharp
class Program
{
	static OxideMod mod;

	static void Main(string[] args)
	{
		CreateRequiredDirectories();

		mod = new OxideMod((string message) =>
		{
	
		});

		// Doing this because it throws NRE in Covalence ctor
		typeof(Interface).GetProperty("Oxide").SetValue(Interface.Oxide, mod, null);

		mod.Load();

		Console.ReadLine();
	}

	static void CreateRequiredDirectories()
	{
		string dir = Environment.CurrentDirectory;

		string extDir = Path.Combine(dir, "Extensions");

		if (!Directory.Exists(extDir))
			Directory.CreateDirectory(extDir);
	}
}
```
oxide.config.json
```json
{
    "CustomConsole": true,
    "InstanceCommandLines":
    [
        "{oxide.directory}",
        "server\\{server.identity}\\oxide",
        "server"
    ],
    "ConfigDirectory": "config",
    "ExtensionDirectory": "Extensions"
}
```
But then it throws a lot of exceptions (when loading JS, Lua, Python extensions):
```
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
Exception thrown: 'System.NullReferenceException' in Oxide.Core.dll
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
Exception thrown: 'System.NullReferenceException' in Oxide.Core.dll
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
Exception thrown: 'System.IO.FileNotFoundException' in Oxide.Core.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception thrown: 'System.IO.FileNotFoundException' in Oxide.Core.dll
Exception thrown: 'System.IO.FileNotFoundException' in Oxide.Core.dll
Exception thrown: 'System.Reflection.ReflectionTypeLoadException' in mscorlib.dll
Exception thrown: 'System.Reflection.ReflectionTypeLoadException' in mscorlib.dll
Exception thrown: 'System.Reflection.ReflectionTypeLoadException' in mscorlib.dll
```
Can you give me some help on this? Maybe information about how Oxide works (i mean when it loads extensions and stuff). Thank you.

**Comment by lukespragg** [comment]
I'm not saying it's not possible (given a good bit of work), but there just isn't anything setup for that and right now. I imagine the NREs and such are going to be caused by missing DLLs and dependencies.
