### ISSUE TITLE
Snapshot Oxide for Rust under Linux

### ISSUE THREAD

**Issue by fribergr** [OxideMod/Oxide#887]
Hi,

Since this morning, the snapshot for OxideMod in Rust running under linux is no longer available. This is due to commit:

https://github.com/OxideMod/Snapshots/commit/dce648ea01577cf1a25b1a9eed53f609ae272572

Could you please redirect me to the new URL (if any) or re-publish the compiled Linux-binaries?

Thanks!

**Comment by lukespragg** [comment]
They're under the same build .zip now.
