### ISSUE TITLE
'pdb2mdb' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Emidomenge** [OxideMod/Oxide#904]
Hello,

I have some troubles to build the project.

I've got : 
```
'pdb2mdb' is not recognized as an internal or external command,
operable program or batch file.
```

I have VS Studio 2015 last version.

Thanks for help

**Comment by lukespragg** [comment]
Unless you need a debug build, switch to release and use that. If you need the mdb files, you'd need to download pdb2mdb for use with the debug build.
