### ISSUE TITLE
Required dependent plugin loading after other plugin

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#935]
As reported by @LaserHydra, not sure if the plugins are just setup oddly or what.

![1d9f9692dd8a4e579e054583819a800d](https://cloud.githubusercontent.com/assets/671337/20569501/4d855e80-b16e-11e6-8c18-9314389d8cd7.png)

**Comment by bazuka5801** [comment]
Hi, i need fix it, i offer my solution:
create Attribute(int loadIndex = 0) // 0 - default, can (i<0), first loading) and (i>0, last loading)
nonattribute plugins defaul set loadindex = 0; .
put sort code for pluginsloadint to your loader
