### ISSUE TITLE
Better installation steps for custom builds

### ISSUE THREAD

**Issue by bgourlie** [OxideMod/Oxide#96]
Docs are unclear how to really get started with this.  If you clarify some questions for me I'd be more than willing to submit a PR for the readme.

Where does `Oxide.Core.dll go`?  In the same directory as `RustDedicated.exe`?

What file is the patcher actually patching?  The whole project concept is confusing and not well explained.  The patcher just makes it so that the Oxide core dll gets loaded, right?

The readme says that the `Oxide.Ext.*.dll` files are loaded from the binary folder.  Where exactly is the binary folder?

Thanks for any clarification.

**Comment by lukespragg** [comment]
The readme is a bit dated, and will likely be mostly scrapped soon, as newer docs are being made and exist.

http://forum.rustoxide.com/threads/setting-up-your-own-experimental-rust-server-with-oxide-2.5754/

**Comment by bgourlie** [comment]
Installing using those instructions crashes when starting up the latest dev branch server.  I assume that I need to patch the latest files?  I guess that's the part that is kind confusing...  I guess I'm looking for more developer-centric docs.  I have both the Oxide and OxidePatcher projects building.

**Comment by lukespragg** [comment]
The dev server isn't supported, and there is no updated .opj for it publicly.

**Comment by lukespragg** [comment]
I'm not sure if you noticed or not, but each game has its own bundle under the ```bundles``` folder now, which you can copy/paste the contents of that into the appropriate server install.
