### ISSUE TITLE
Compiled DLL loading for advanced plugins and more

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/Oxide#973]
Allowing DLLs to be loaded would be a step toward more complex plugins that can be made up of multiple files instead of a single one. This would also allow the CSharpCompiler to be used primarily for development use if desired, and hopefully prevent issues where users do not have it setup properly or lack the access to set it up properly without host interaction.

Publicly submitted plugins would still be required to not be obfuscated though.

**Comment by Kris-** [comment]
I think this is prevented for security measures on shared hosting setups. I do wish there was a config somewhere that let you lift these limits however.

A last resort would be to compile Oxide yourself, but for me that is too much work for every update.

**Comment by Kris-** [comment]
+1

**Comment by lukespragg** [comment]
DLLs do not provide security, they are as easily readable as .cs files.
